"""Internal backend-neutral IR for TorchLens capture unification."""

from __future__ import annotations

from .buffer import (
    CaptureEvents,
    LiveOpRecord,
    live_record_for_label,
    register_live_event,
    replace_op_event,
)
from .container import ContainerSpec
from .container_registry import (
    ContainerLeafOccurrence,
    ContainerRecord,
    ContainerRegistry,
    ContainerSnapshot,
    FuncSite,
    IdentityEntry,
    ModelSite,
    ModuleSite,
    Phase,
    Role,
)
from .events import (
    ArgTemplateRef,
    BackwardPassEnd,
    BackwardPassStart,
    BlobRef,
    BufferEvent,
    BufferWriteEvent,
    ConditionalEvent,
    EdgeUseKind,
    FunctionCallRef,
    GradFnDiscovered,
    GradFnFired,
    InterventionState,
    ModuleEnterEvent,
    ModuleEvent,
    ModuleExitEvent,
    ModuleFrame,
    ModulePrepEvent,
    OpEvent,
    OpEventKind,
    OpGradObserved,
    OutputRef,
    OutputVersionEvent,
    ParentEdge,
    TraceBuildState,
    edge_use_kind,
    is_control_edge_use,
    is_value_edge_use,
)
from .intervention import FireResult, FunctionEventInput, InterventionTemplateRef
from .live_index import LiveIndex, LiveIndexWindowError
from .predicate import (
    MLXValueUnavailableError,
    RecordContext,
    _DEFERRED_VALUE,
    coerce_deferred_value,
    is_deferred_value,
)
from .refs import DeferredRef, DeviceRef, DtypeRef, ParamRef, ReservedLabel, TensorRef
from .semantics import BackendSemantics, CapturePolicy

__all__ = [
    "ArgTemplateRef",
    "BackendSemantics",
    "BackwardPassEnd",
    "BackwardPassStart",
    "BlobRef",
    "BufferEvent",
    "BufferWriteEvent",
    "CaptureEvents",
    "CapturePolicy",
    "ConditionalEvent",
    "ContainerSpec",
    "ContainerLeafOccurrence",
    "ContainerRecord",
    "ContainerRegistry",
    "ContainerSnapshot",
    "DeferredRef",
    "DeviceRef",
    "DtypeRef",
    "EdgeUseKind",
    "edge_use_kind",
    "FireResult",
    "FunctionCallRef",
    "FunctionEventInput",
    "FuncSite",
    "IdentityEntry",
    "InterventionState",
    "InterventionTemplateRef",
    "is_control_edge_use",
    "is_value_edge_use",
    "GradFnDiscovered",
    "GradFnFired",
    "LiveOpRecord",
    "LiveIndex",
    "LiveIndexWindowError",
    "MLXValueUnavailableError",
    "ModuleEnterEvent",
    "ModuleEvent",
    "ModuleExitEvent",
    "ModuleFrame",
    "ModulePrepEvent",
    "ModelSite",
    "ModuleSite",
    "OpEvent",
    "OpEventKind",
    "OpGradObserved",
    "OutputRef",
    "OutputVersionEvent",
    "ParamRef",
    "ParentEdge",
    "Phase",
    "RecordContext",
    "ReservedLabel",
    "Role",
    "TensorRef",
    "TraceBuildState",
    "_DEFERRED_VALUE",
    "coerce_deferred_value",
    "is_deferred_value",
    "live_record_for_label",
    "register_live_event",
    "replace_op_event",
]
