"""Phase 9 bundle diff renderer snapshot tests."""

from __future__ import annotations

import re
from io import BytesIO
from pathlib import Path
from typing import Any

import numpy as np
import pytest
import torch

import torchlens as tl
from torchlens.intervention import MultiMatchWarning

SNAPSHOT_DIR = Path(__file__).parent / "snapshots"
GOLDEN_SVG = SNAPSHOT_DIR / "bundle_diff_clean_vs_zero_relu.svg"


def _canonical_bundle() -> tl.Bundle:
    """Return the canonical Phase 9 clean-vs-ablated ResNet-18 bundle.

    Returns
    -------
    tl.Bundle
        Bundle with ``clean`` and ``ablated`` members.
    """

    torchvision_models = pytest.importorskip("torchvision.models")
    torch.manual_seed(0)
    model = torchvision_models.resnet18(weights=None).eval()
    x = torch.randn(1, 3, 224, 224)
    model_log = tl.log_forward_pass(model, x, vis_opt="none", intervention_ready=True)
    ablated_log = model_log.fork("ablated")
    with pytest.warns(MultiMatchWarning):
        ablated_log.do(
            tl.module("layer1.0.relu"),
            tl.zero_ablate(),
            confirm_mutation=True,
        )
    return tl.bundle({"clean": model_log, "ablated": ablated_log}, baseline="clean")


def _normalize_svg(svg: str) -> bytes:
    """Normalize semantic SVG text before byte comparison.

    Parameters
    ----------
    svg:
        Raw SVG text.

    Returns
    -------
    bytes
        Normalized UTF-8 payload.
    """

    normalized = re.sub(r'id="node\d+"', 'id="node"', svg)
    normalized = re.sub(r'id="edge\d+"', 'id="edge"', normalized)
    normalized = re.sub(r"<!-- Generated by graphviz version .*?-->", "", normalized, flags=re.S)
    normalized = re.sub(r"<!-- Title: .*?-->", "", normalized)
    normalized = re.sub(r"<!-- Pages: .*?-->", "", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip()
    return normalized.encode("utf-8")


def _rasterize(svg_path: Path) -> np.ndarray[Any, np.dtype[np.uint8]]:
    """Rasterize an SVG file to an RGB pixel array.

    Parameters
    ----------
    svg_path:
        SVG file path.

    Returns
    -------
    np.ndarray[Any, np.dtype[np.uint8]]
        RGB pixel data.
    """

    cairosvg = pytest.importorskip("cairosvg")
    pillow_image = pytest.importorskip("PIL.Image")
    png_bytes = cairosvg.svg2png(url=str(svg_path), output_width=1200, output_height=800)
    image = pillow_image.open(BytesIO(png_bytes)).convert("RGB")
    return np.asarray(image, dtype=np.uint8)


def _pixel_similarity(candidate_path: Path, reference_path: Path) -> float:
    """Return a normalized pixel similarity score for two SVG files.

    Parameters
    ----------
    candidate_path:
        Candidate SVG path.
    reference_path:
        Reference SVG path.

    Returns
    -------
    float
        Similarity in ``[0, 1]``.
    """

    candidate = _rasterize(candidate_path).astype(np.float32)
    reference = _rasterize(reference_path).astype(np.float32)
    if candidate.shape != reference.shape:
        return 0.0
    mean_abs = float(np.mean(np.abs(candidate - reference)))
    return max(0.0, 1.0 - (mean_abs / 255.0))


def test_bundle_diff_canonical_resnet_snapshot(tmp_path: Path) -> None:
    """Canonical hero demo matches normalized SVG or image threshold."""

    bundle = _canonical_bundle()
    outpath = tmp_path / "bundle_diff_clean_vs_zero_relu"
    dot_source = bundle.show_diff(vis_outpath=str(outpath), vis_save_only=True)
    candidate_svg = outpath.with_suffix(".svg")

    assert dot_source.startswith("// TorchLens bundle diff")
    assert candidate_svg.exists()
    assert "aria-label=" in candidate_svg.read_text(encoding="utf-8")
    assert len(bundle.aligned_pairs("clean", "ablated")) > 0

    candidate_normalized = _normalize_svg(candidate_svg.read_text(encoding="utf-8"))
    reference_normalized = _normalize_svg(GOLDEN_SVG.read_text(encoding="utf-8"))
    if candidate_normalized == reference_normalized:
        return

    similarity = _pixel_similarity(candidate_svg, GOLDEN_SVG)
    assert similarity >= 0.95
