"""F10 golden-specimen corpus + ascii==degrade sweep (the row gate).

Every specimen is GENERATED by the real formatter (D33) -- the byte pins
below were produced by the code under test on fully deterministic inputs
(arange-built tensors and an elementwise model, so no reduction-order or
RNG dependence) and then frozen in-source. Goldens key on stable
addresses, never global-counter op labels (D33). The ascii==degrade
byte-contract runs over EVERY specimen in this corpus.
"""

from __future__ import annotations

import pytest
import torch
from torch import nn

import torchlens as tl
from torchlens.stats import degrade, glance, render_core_line, tensor_stats

pytestmark = pytest.mark.smoke


def _arange(*shape: int, offset: float = 0.0) -> torch.Tensor:
    """Fully deterministic float tensor (no RNG, no reductions)."""

    numel = 1
    for dim in shape:
        numel *= dim
    return (torch.arange(numel, dtype=torch.float32).reshape(*shape) / 7.0) + offset


#: (name, tensor factory, expected ASCII core line) -- generated by
#: render_core_line on torch 2.13 CPU; arithmetic is elementwise/exact.
_CORE_SPECIMENS = [
    (
        "arange_2d",
        lambda: _arange(4, 8),
        "f32[4,8]@cpu n=32 [0.000 %********% 4.429] mean=2.214 sd=1.319 zero=1/32",
    ),
    (
        "small_ints",
        lambda: torch.arange(8, dtype=torch.int64),
        "i64[8]@cpu [0 1 2 3 4 5 6 7] mean=3.500 sd=2.291 zero=1/8",
    ),
    (
        "scalar",
        lambda: torch.tensor(8, dtype=torch.int64),
        "i64[]@cpu = 8",
    ),
    (
        "all_zero",
        lambda: torch.zeros(3, 4),
        "f32[3,4]@cpu n=12 all_zero",
    ),
    (
        "constant",
        lambda: torch.full((5, 5), 2.5),
        "f32[5,5]@cpu n=25 constant=2.500",
    ),
    (
        "bool_all_true",
        lambda: torch.ones(2, 4, dtype=torch.bool),
        "bool[2,4]@cpu n=8 all_true",
    ),
    (
        "poisoned",
        lambda: torch.tensor([[1.0, float("nan")], [float("inf"), -float("inf")]]),
        "f32[2,2]@cpu n=4 [1.000 nan inf -inf] mean=1.000 sd=0.000 nan=25%! +inf=25%! -inf=25%!",
    ),
    (
        "empty",
        lambda: torch.empty(0),
        "f32[0]@cpu empty",
    ),
]


@pytest.mark.parametrize(
    "name,factory,expected", _CORE_SPECIMENS, ids=[s[0] for s in _CORE_SPECIMENS]
)
def test_core_line_golden(name: str, factory, expected: str) -> None:
    """Byte-pinned core lines from the real formatter (D33)."""

    line = glance(factory())
    assert line == expected, f"{name}: {line!r}"


@pytest.mark.parametrize(
    "name,factory,expected", _CORE_SPECIMENS, ids=[s[0] for s in _CORE_SPECIMENS]
)
def test_ascii_equals_degrade_unicode(name: str, factory, expected: str) -> None:
    """The row-gate byte contract: ascii == degrade(unicode), per specimen."""

    tensor = factory()
    ascii_line = glance(tensor, style="ascii")
    unicode_line = glance(tensor, style="unicode")
    assert ascii_line == degrade(unicode_line)
    assert ascii_line.isascii()


class _Elementwise(nn.Module):
    """Deterministic elementwise model (no matmul: no reduction order)."""

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        v = x.view(-1)
        r = torch.relu(v - 0.5)
        return r.clone()


def _elementwise_trace() -> tl.Trace:
    """One deterministic capture (arange input, elementwise ops only)."""

    return tl.trace(
        _Elementwise().eval(),
        _arange(2, 4),
        capture=tl.options.CaptureOptions(intervention_ready=True),
    )


def test_op_envelope_golden() -> None:
    """Byte-pinned envelope+core line and card for a real captured op.

    The relu site is addressed through its stable label in THIS fixed
    model (single capture, no config dependence -- the D33 concern is
    checkpoint/config-variant corpora; this model is frozen in-source).
    """

    trace = _elementwise_trace()
    op = trace["relu_1_3"].ops[0]
    assert repr(op) == (
        "_Elementwise/relu_1_3 (pass 1/1) [op 3/4 relu] -> "
        "f32[8]@cpu [0.000 .. 0.5000] mean=0.1429 sd=0.1821 zero=4/8"
    )
    card = str(op)
    lines = card.splitlines()
    assert lines[0] == repr(op)
    assert any(line.strip().startswith("graph") for line in lines)
    assert any(line.strip().startswith("func") for line in lines)
    assert lines[-1].strip().startswith("More:")
    trace.cleanup()


def test_trace_and_records_ascii_sweep() -> None:
    """Every rendered surface of a capture is pure ASCII by default."""

    trace = _elementwise_trace()
    surfaces = [repr(trace), str(trace), repr(trace.layers), str(trace.layers)]
    surfaces.extend(repr(op) for op in trace.layer_list)
    surfaces.extend(str(op) for op in trace.layer_list)
    surfaces.extend(repr(trace.stats_table()))
    for text in surfaces:
        assert text.isascii(), text[:80]
    trace.cleanup()


def test_stats_record_repr_is_the_core_line() -> None:
    """TensorStats reprs as its own grammar (records show)."""

    stats = tensor_stats(_arange(4, 8))
    assert repr(stats) == f"TensorStats({render_core_line(stats)})"
