"""Artifact packet generator for the netron visual signoff (F14, memo s9).

The packet is generated by the SAME harnesses that gate CI, so the reviewer
confirms a stated number instead of forming an impression: per artifact, an
auto-generated ``EXPECTED-APPEARANCE.md`` (node/IO counts, edge-label count
with sample strings, function list with per-function node counts, one
node's full sidebar payload) and one machine-readable ``manifest.json``
(versions, options, SHA-256, counts, typed values, hidden buffers,
attachment targets, bytes, export time). Screenshots and the attachment
drag-drop remain the D03 browser-packet lane's human steps.

Run stand-alone to build a packet from the available fixture roster::

    python tests/test_netron_export_packet.py <outdir>
"""

from __future__ import annotations

import hashlib
import json
import sys
import time
import warnings
from pathlib import Path
from typing import Any

import pytest
import torch
from torch import nn

import torchlens as tl


def _artifact_row(name: str, path: Path, options: dict[str, Any], seconds: float) -> dict:
    """Build one manifest row from an exported artifact."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    props = {row["key"]: row["value"] for row in payload["metadataProps"]}
    graph = payload["graph"]
    edge_labels = [row["name"] for row in graph.get("valueInfo", []) if row.get("type") is not None]
    companion = path.with_name(path.stem + ".attachment.json")
    attachment_targets = 0
    if companion.exists():
        sidecar = json.loads(companion.read_text(encoding="utf-8"))
        attachment_targets = len(
            {item.get("target") for item in sidecar["metadata"] + sidecar["metrics"]}
        )
    return {
        "name": name,
        "file": path.name,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "bytes": path.stat().st_size,
        "export_seconds": round(seconds, 3),
        "options": options,
        "torchlens_version": str(getattr(tl, "__version__", "")),
        "torch_version": torch.__version__,
        "node_count": int(props["torchlens.node_count"]),
        "edge_count": int(props["torchlens.edge_count"]),
        "function_count": int(props["torchlens.function_count"]),
        "typed_value_count": len(edge_labels),
        "graph_inputs": len(graph.get("input", [])),
        "graph_outputs": len(graph.get("output", [])),
        "hidden_buffer_count": int(props["torchlens.hidden_buffer_count"]),
        "hidden_op_count": int(props["torchlens.hidden_op_count"]),
        "omitted_value_count": int(props["torchlens.omitted_value_count"]),
        "capture_outcome": props.get("torchlens.capture_outcome", ""),
        "attachment_targets": attachment_targets,
    }


def _expected_appearance(name: str, path: Path) -> str:
    """Render one artifact's EXPECTED-APPEARANCE.md body (memo s9)."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    graph = payload["graph"]
    lines = [f"# EXPECTED APPEARANCE -- {name}", ""]
    lines.append(f"- root boxes: {len(graph['node'])} nodes")
    lines.append(
        f"- graph I/O: {len(graph.get('input', []))} input(s), "
        f"{len(graph.get('output', []))} output(s) (drawn as boxes too)"
    )
    samples = []
    for row in graph.get("valueInfo", [])[:3]:
        dims = row.get("type", {}).get("tensorType", {}).get("shape", {}).get("dim", [])
        samples.append("x".join(d.get("dimValue", d.get("dimParam", "?")) for d in dims))
    lines.append(
        f"- painted edge labels: {len(graph.get('valueInfo', []))} typed values; "
        f"samples: {', '.join(samples) or '(none)'}"
    )
    functions = payload.get("functions", [])
    lines.append(f"- functions ({len(functions)}), per-body node counts:")
    for function in functions:
        lines.append(f"  - {function['name']}: {len(function['node'])} nodes")
    probe = next((node for node in graph["node"] if node.get("attribute")), None)
    if probe is not None:
        lines.append(f"- sidebar payload for `{probe['name']}`:")
        for attr in probe["attribute"]:
            value = attr.get("i") or attr.get("f") or attr.get("ints") or "(string)"
            lines.append(f"  - {attr['name']} = {value}")
    lines.append("")
    lines.append("Reviewer checklist: legibility at fit zoom; no overlaps or blank")
    lines.append("panels; function icon discoverable; unavailable-is-absent; neutral")
    lines.append("charcoal is netron's default dark node style, not missing data.")
    return "\n".join(lines) + "\n"


def build_packet(fixtures: dict[str, Any], outdir: Path) -> Path:
    """Export the fixture roster and write the packet manifest + appearances.

    Parameters
    ----------
    fixtures:
        Name -> finished ``Trace``; each exports at op AND module granularity
        (module carries the attachment companion).
    outdir:
        Packet destination directory.

    Returns
    -------
    Path
        The written ``manifest.json``.
    """

    outdir.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, log in fixtures.items():
        for granularity in ("op", "module"):
            options: dict[str, Any] = {"granularity": granularity}
            attachment = granularity == "module"
            start = time.perf_counter()
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                path = tl.export.netron(
                    log,
                    outdir / f"{name}_{granularity}.json",
                    granularity=granularity,
                    attachment=attachment,
                )
            seconds = time.perf_counter() - start
            rows.append(_artifact_row(f"{name}/{granularity}", path, options, seconds))
            (outdir / f"{name}_{granularity}.EXPECTED-APPEARANCE.md").write_text(
                _expected_appearance(f"{name}/{granularity}", path), encoding="utf-8"
            )
    manifest = outdir / "manifest.json"
    manifest.write_text(json.dumps({"artifacts": rows}, indent=2), encoding="utf-8")
    return manifest


def _toy_fixtures() -> dict[str, Any]:
    """The download-free PR fixture roster (memo s6 real-model plan)."""

    class _Inner(nn.Module):
        """Two-op child."""

        def __init__(self) -> None:
            """Build the linear layer."""

            super().__init__()
            self.fc = nn.Linear(4, 4)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            """Linear then relu."""

            return torch.relu(self.fc(x))

    class _Nested(nn.Module):
        """Two children plus a root op."""

        def __init__(self) -> None:
            """Build children."""

            super().__init__()
            self.a = _Inner()
            self.b = _Inner()

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            """Combine children."""

            return self.a(x) + self.b(x)

    class _Loop(nn.Module):
        """Recurrent two-op loop (pass-qualified IDs)."""

        def __init__(self) -> None:
            """Build the reused linear layer."""

            super().__init__()
            self.fc = nn.Linear(4, 4)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            """Three recurrent passes."""

            for _ in range(3):
                x = torch.tanh(self.fc(x))
            return x

    class _TwoOut(nn.Module):
        """Aliased-output fixture."""

        def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
            """Same tensor twice."""

            y = torch.relu(x)
            return y, y

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        train_bn = tl.trace(
            nn.Sequential(nn.Linear(4, 4), nn.BatchNorm1d(4)).train(), torch.randn(2, 4)
        )
    return {
        "nested": tl.trace(_Nested(), torch.randn(2, 4)),
        "recurrent": tl.trace(_Loop(), torch.randn(2, 4)),
        "train_batchnorm": train_bn,
        "aliased_outputs": tl.trace(_TwoOut(), torch.randn(2, 4)),
    }


@pytest.mark.smoke
def test_packet_generator_builds_manifest_and_appearances(tmp_path: Path) -> None:
    """The mini packet carries every promised manifest field per artifact."""

    manifest_path = build_packet(_toy_fixtures(), tmp_path / "packet")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert len(manifest["artifacts"]) == 8  # 4 fixtures x 2 granularities
    required = {
        "name",
        "sha256",
        "bytes",
        "export_seconds",
        "options",
        "node_count",
        "edge_count",
        "function_count",
        "typed_value_count",
        "hidden_buffer_count",
        "attachment_targets",
        "capture_outcome",
    }
    for row in manifest["artifacts"]:
        assert required <= set(row), f"manifest row missing {required - set(row)}"
    module_rows = [r for r in manifest["artifacts"] if r["options"]["granularity"] == "module"]
    assert all(row["attachment_targets"] > 0 for row in module_rows)
    appearance = (manifest_path.parent / "nested_module.EXPECTED-APPEARANCE.md").read_text(
        encoding="utf-8"
    )
    assert "root boxes" in appearance and "sidebar payload" in appearance


@pytest.mark.heavy
def test_resnet18_architecture_real_row(tmp_path: Path) -> None:
    """The REALISM-RULE PR fixture: torchvision resnet18, weights=None.

    Weights change no exported structure, so the architecture-real capture
    is sufficient for PR speed (memo s6); the checkpoint roster belongs to
    the scheduled/release packet (D03).
    """

    torchvision = pytest.importorskip("torchvision")
    onnx = pytest.importorskip("onnx")
    json_format = pytest.importorskip("google.protobuf.json_format")

    log = tl.trace(torchvision.models.resnet18(weights=None).eval(), torch.randn(1, 3, 224, 224))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        path = tl.export.netron(log, tmp_path / "resnet18.json", attachment=True)
    model = json_format.Parse(path.read_text(encoding="utf-8"), onnx.ModelProto())
    onnx.checker.check_model(model, full_check=True)
    payload = json.loads(path.read_text(encoding="utf-8"))
    props = {row["key"]: row["value"] for row in payload["metadataProps"]}
    assert int(props["torchlens.function_count"]) >= 8, "the residual stages drill down"
    assert len(payload["graph"]["node"]) <= 20, "the shallow module view is a diagram"
    assert int(props["torchlens.hidden_buffer_count"]) == 80, "eval resnet18 buffer census"


if __name__ == "__main__":
    destination = Path(sys.argv[1] if len(sys.argv) > 1 else "netron_packet")
    fixture_roster = _toy_fixtures()
    try:
        import torchvision as _torchvision

        fixture_roster["resnet18"] = tl.trace(
            _torchvision.models.resnet18(weights=None).eval(), torch.randn(1, 3, 224, 224)
        )
    except ImportError:
        pass
    print(build_packet(fixture_roster, destination))
