"""Phase 9 bundle diff renderer snapshot tests."""

from __future__ import annotations

import re
from io import BytesIO
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from xml.etree import ElementTree

import numpy as np
import pytest
import torch

import torchlens as tl
from torchlens.intervention import MultiMatchWarning
from torchlens.visualization.bundle_diff import _add_svg_accessibility, _build_dot, _select_pairs

SNAPSHOT_DIR = Path(__file__).parent / "snapshots"
GOLDEN_SVG = SNAPSHOT_DIR / "bundle_diff_clean_vs_zero_relu.svg"


def _canonical_bundle() -> tl.Bundle:
    """Return the canonical Phase 9 clean-vs-ablated ResNet-18 bundle.

    Returns
    -------
    tl.Bundle
        Bundle with ``clean`` and ``ablated`` members.
    """

    torchvision_models = pytest.importorskip("torchvision.models")
    torch.manual_seed(0)
    model = torchvision_models.resnet18(weights=None).eval()
    x = torch.randn(1, 3, 224, 224)
    trace = tl.trace(model, x, intervention_ready=True)
    ablated_log = trace.fork("ablated")
    with pytest.warns(MultiMatchWarning):
        ablated_log.do(
            tl.module("layer1.0.relu"),
            tl.zero_ablate(),
            confirm_mutation=True,
        )
    return tl.bundle({"clean": trace, "ablated": ablated_log}, baseline="clean")


def _normalize_svg(svg: str) -> bytes:
    """Normalize semantic SVG text before byte comparison.

    Parameters
    ----------
    svg:
        Raw SVG text.

    Returns
    -------
    bytes
        Normalized UTF-8 payload.
    """

    normalized = re.sub(r'id="node\d+"', 'id="node"', svg)
    normalized = re.sub(r'id="edge\d+"', 'id="edge"', normalized)
    normalized = re.sub(r"<!-- Generated by graphviz version .*?-->", "", normalized, flags=re.S)
    normalized = re.sub(r"<!-- Title: .*?-->", "", normalized)
    normalized = re.sub(r"<!-- Pages: .*?-->", "", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip()
    return normalized.encode("utf-8")


def _rasterize(svg_path: Path) -> np.ndarray[Any, np.dtype[np.uint8]]:
    """Rasterize an SVG file to an RGB pixel array.

    Parameters
    ----------
    svg_path:
        SVG file path.

    Returns
    -------
    np.ndarray[Any, np.dtype[np.uint8]]
        RGB pixel data.
    """

    cairosvg = pytest.importorskip("cairosvg")
    pillow_image = pytest.importorskip("PIL.Image")
    png_bytes = cairosvg.svg2png(url=str(svg_path), output_width=1200, output_height=800)
    image = pillow_image.open(BytesIO(png_bytes)).convert("RGB")
    return np.asarray(image, dtype=np.uint8)


def _pixel_similarity(candidate_path: Path, reference_path: Path) -> float:
    """Return a normalized pixel similarity score for two SVG files.

    Parameters
    ----------
    candidate_path:
        Candidate SVG path.
    reference_path:
        Reference SVG path.

    Returns
    -------
    float
        Similarity in ``[0, 1]``.
    """

    candidate = _rasterize(candidate_path).astype(np.float32)
    reference = _rasterize(reference_path).astype(np.float32)
    if candidate.shape != reference.shape:
        return 0.0
    mean_abs = float(np.mean(np.abs(candidate - reference)))
    return max(0.0, 1.0 - (mean_abs / 255.0))


def test_bundle_diff_canonical_resnet_snapshot(tmp_path: Path) -> None:
    """Canonical hero demo matches normalized SVG or image threshold."""

    bundle = _canonical_bundle()
    outpath = tmp_path / "bundle_diff_clean_vs_zero_relu"
    dot_source = bundle.show_diff(vis_outpath=str(outpath), vis_save_only=True)
    candidate_svg = outpath.with_suffix(".svg")

    assert dot_source.startswith("// TorchLens bundle diff")
    assert candidate_svg.exists()
    svg_text = candidate_svg.read_text(encoding="utf-8")
    assert "aria-label=" in svg_text
    assert "clean vs ablated" in svg_text
    assert "zero_ablate(layer1.0.relu)" not in svg_text
    assert len(bundle.aligned_pairs("clean", "ablated")) > 0

    candidate_normalized = _normalize_svg(svg_text)
    reference_normalized = _normalize_svg(GOLDEN_SVG.read_text(encoding="utf-8"))
    if candidate_normalized == reference_normalized:
        return

    similarity = _pixel_similarity(candidate_svg, GOLDEN_SVG)
    assert similarity >= 0.95


def test_bundle_diff_caption_uses_selected_members(tmp_path: Path) -> None:
    """Bundle diff captions should describe the actual rendered comparison."""

    torch.manual_seed(0)
    model = torch.nn.Linear(3, 2).eval()
    left = tl.trace(model, torch.randn(1, 3))
    right = left.fork("patched")
    bundle = tl.bundle({"base": left, "patched": right}, baseline="base")

    outpath = tmp_path / "member_caption"
    dot_source = bundle.show_diff(
        left="base",
        right="patched",
        vis_outpath=str(outpath),
        vis_save_only=True,
    )
    svg_text = outpath.with_suffix(".svg").read_text(encoding="utf-8")

    assert "base vs patched" in dot_source
    assert "columns: base, patched" in dot_source
    assert "layer1.0.relu" not in dot_source
    assert "top: clean, bottom: ablated" not in dot_source
    assert "base versus patched" in svg_text


def test_bundle_diff_uses_each_members_own_delta() -> None:
    """Left and right clusters show their own deltas from a custom baseline."""

    left_layer = SimpleNamespace(layer_label="left_1", func_name="op", parents=[], shape=None)
    right_layer = SimpleNamespace(layer_label="right_1", func_name="op", parents=[], shape=None)
    bundle = {
        "baseline": SimpleNamespace(layer_list=[]),
        "left": SimpleNamespace(layer_list=[left_layer]),
        "right": SimpleNamespace(layer_list=[right_layer]),
    }

    dot = _build_dot(
        pairs=[(left_layer, right_layer)],
        bundle=bundle,
        left_name="left",
        right_name="right",
        metric_name="relative_l2",
        tensor_field="out",
        delta_map={"node_1": {"baseline": 0.0, "left": 1.25, "right": 5.5}},
        layer_to_node={"left_1": "node_1", "right_1": "node_1"},
        theme_name="paper",
        include_unmatched=False,
    )
    source = dot.source

    assert re.search('clean_left_1 \\[.*label="left_1\nop\ndelta=1.25"', source, re.S)
    assert re.search('intervention_right_1 \\[.*label="right_1\nop\ndelta=5.5"', source, re.S)


def test_bundle_diff_pair_selection_considers_left_delta() -> None:
    """Top-pair selection uses both members' own baseline deltas."""

    left_high = SimpleNamespace(layer_label="left_high")
    right_low = SimpleNamespace(layer_label="right_low")
    left_low = SimpleNamespace(layer_label="left_low")
    right_mid = SimpleNamespace(layer_label="right_mid")

    selected = _select_pairs(
        [(left_high, right_low), (left_low, right_mid)],
        left_name="left",
        right_name="right",
        delta_map={
            "node_high": {"left": 9.0, "right": 0.0},
            "node_mid": {"left": 0.0, "right": 5.0},
        },
        layer_to_node={
            "left_high": "node_high",
            "right_low": "node_high",
            "left_low": "node_mid",
            "right_mid": "node_mid",
        },
        max_pairs=1,
    )

    assert selected == [(left_high, right_low)]


def test_bundle_diff_svg_accessibility_escapes_quotes(tmp_path: Path) -> None:
    """SVG aria labels remain valid XML when member names contain quotes."""

    svg_path = tmp_path / "quoted.svg"
    svg_path.write_text('<svg width="1" height="1"></svg>', encoding="utf-8")

    _add_svg_accessibility(str(svg_path), 'left "quoted" versus right')

    svg_text = svg_path.read_text(encoding="utf-8")
    assert 'aria-label="left &quot;quoted&quot; versus right"' in svg_text
    ElementTree.fromstring(svg_text)
