"""Coverage gate for decorated torch argument extraction specs."""

from __future__ import annotations

import pytest
import torch

from torchlens.capture.arg_positions import (
    FUNC_ARG_SPECS,
    ArgSpec,
    _cache_dynamic_spec,
    _normalize_func_name,
)
from torchlens.constants import ORIG_TORCH_FUNCS


_HIGH_CONFIDENCE_STATIC_NAMES = frozenset(
    {
        "adaptivemaxpool1dwithindices",
        "adaptivemaxpool2dwithindices",
        "adaptivemaxpool3dwithindices",
        "addr",
        "airyai",
        "alignas",
        "aminmax",
        "argwhere",
        "besselj0",
        "besselj1",
        "bessely0",
        "bessely1",
        "binarycrossentropy",
        "bucketize",
        "cdist",
        "chainmatmul",
        "chebyshevpolynomialt",
        "chebyshevpolynomialu",
        "chebyshevpolynomialv",
        "chebyshevpolynomialw",
        "choleskyex",
        "choleskyinverse",
        "cond",
        "corrcoef",
        "cov",
        "cumulativetrapezoid",
        "dequantize",
        "diff",
        "dropout1d",
        "entr",
        "erfcx",
        "fakequantizeperchannelaffine",
        "fakequantizepertensoraffine",
        "frexp",
        "gammainc",
        "gammaincc",
        "gammaln",
        "gcd",
        "geqrf",
        "ger",
        "glu",
        "gradient",
        "gumbelsoftmax",
        "hermitepolynomialh",
        "hermitepolynomialhe",
        "hfftn",
        "hspmm",
        "igamma",
        "igammac",
        "ihfftn",
        "inv",
        "invex",
        "isconj",
        "isin",
        "isinference",
        "isnonzero",
        "issetto",
        "laguerrepolynomiall",
        "lcm",
        "ldexp",
        "ldlfactor",
        "ldlfactorex",
        "ldlsolve",
        "legendrepolynomialp",
        "lobpcg",
        "localresponsenorm",
        "logaddexp",
        "logaddexp2",
        "logndtr",
        "lppool3d",
        "lufactor",
        "lufactorex",
        "map",
        "modifiedbesseli0",
        "modifiedbesseli1",
        "modifiedbesselk0",
        "modifiedbesselk1",
        "moduleload",
        "multigammaln",
        "multinomial",
        "nanquantile",
        "ndtr",
        "ndtri",
        "normalize",
        "orgqr",
        "ormqr",
        "pairwisedistance",
        "pcalowrank",
        "pdist",
        "pinv",
        "poisson",
        "psi",
        "quantile",
        "quantizeperchannel",
        "quantizepertensor",
        "quantizepertensordynamic",
        "randintlike",
        "renorm",
        "resize",
        "scaledmodifiedbesselk0",
        "scaledmodifiedbesselk1",
        "shiftedchebyshevpolynomialt",
        "shiftedchebyshevpolynomialu",
        "shiftedchebyshevpolynomialv",
        "shiftedchebyshevpolynomialw",
        "smm",
        "softmin",
        "solveex",
        "solvetriangular",
        "sspaddmm",
        "stdmean",
        "svdlowrank",
        "svdvals",
        "tensorinv",
        "tensorsolve",
        "trapezoid",
        "trapz",
        "tripletmarginwithdistanceloss",
        "truncnormal",
        "unravelindex",
        "unsafechunk",
        "unsafesplit",
        "varmean",
        "vecdot",
        "zeta",
    }
)

_KNOWN_UNSUPPORTED_ARG_SPECS = frozenset(
    {
        "addbatchdim",
        "adddocstr",
        "addmmactivation",
        "addrelu",
        "affinegridgenerator",
        "aliascopy",
        "alignto",
        "ampforeachnonfinitecheckandunscale",
        "ampupdatescale",
        "apply",
        "array",
        "arraywrap",
        "assertasync",
        "assertscalar",
        "asserttensormetadata",
        "asstridedcopy",
        "autocast",
        "autocasttofullprecision",
        "autocasttoreducedprecision",
        "backward",
        "batchnormbackwardelemt",
        "batchnormbackwardreduce",
        "batchnormelemt",
        "batchnormgatherstats",
        "batchnormgatherstatswithcounts",
        "batchnormimplindex",
        "batchnormstats",
        "batchnormupdatestats",
        "binarycrossentropywithlogits",
        "binomial",
        "castbyte",
        "castchar",
        "castdouble",
        "castfloat",
        "casthalf",
        "castint",
        "castlong",
        "castshort",
        "ccolindicescopy",
        "chooseqparamsoptimized",
        "chooseqparamspertensor",
        "chunkcat",
        "clearnonserializablecacheddata",
        "coalesced",
        "colindicescopy",
        "computelinearcombination",
        "conjcopy",
        "constantpadnd",
        "convertindicesfromcootocsr",
        "convertindicesfromcsrtocoo",
        "convertweighttoint4pack",
        "convertweighttoint4packforcpu",
        "convolution",
        "convolutionmode",
        "convtbc",
        "copyfrom",
        "copyfromandresize",
        "crowindicescopy",
        "csltcompress",
        "csltsparsemm",
        "csltsparsemmsearch",
        "cudnnconvolutionaddrelu",
        "cudnnctcloss",
        "cudnninitdropoutstate",
        "cudnnrnn",
        "cudnnrnnflattenweight",
        "cufftclearplancache",
        "cufftgetplancachemaxsize",
        "cufftgetplancachesize",
        "cufftsetplancachemaxsize",
        "cummaxhelper",
        "cumminhelper",
        "debughasinternaloverlap",
        "deepcopy",
        "dimarange",
        "dimi",
        "dimorder",
        "dimv",
        "dirichletgrad",
        "dlpack",
        "dlpackdevice",
        "dsmm",
        "dynquantmatmul4bit",
        "dynquantpack4bitweight",
        "efficientzerotensor",
        "embeddingbag",
        "embeddingbagforwardonly",
        "embeddingrenorm",
        "emptyaffinequantized",
        "emptyperchannelaffinequantized",
        "euclideandist",
        "fakequantizelearnableperchannelaffine",
        "fakequantizelearnablepertensoraffine",
        "fakequantizepertensoraffinecachemasktensorqparams",
        "fanmode",
        "fbgemmlinearfp16weight",
        "fbgemmlinearfp16weightfp32activation",
        "fbgemmlinearint8weight",
        "fbgemmlinearint8weightfp32activation",
        "fbgemmlinearquantizeweight",
        "fbgemmpackgemmmatrixfp16",
        "fbgemmpackquantizedmatrix",
        "featuredropout",
        "fftc2c",
        "fftc2r",
        "fftr2c",
        "fillmemeffdropoutmask",
        "floordiv",
        "foobar",
        "foreachabs",
        "foreachacos",
        "foreachadd",
        "foreachaddcdiv",
        "foreachaddcmul",
        "foreachasin",
        "foreachatan",
        "foreachceil",
        "foreachclampmax",
        "foreachclampmin",
        "foreachcopy",
        "foreachcos",
        "foreachcosh",
        "foreachdiv",
        "foreacherf",
        "foreacherfc",
        "foreachexp",
        "foreachexpm1",
        "foreachfloor",
        "foreachfrac",
        "foreachlerp",
        "foreachlgamma",
        "foreachlog",
        "foreachlog10",
        "foreachlog1p",
        "foreachlog2",
        "foreachmax",
        "foreachmaximum",
        "foreachminimum",
        "foreachmul",
        "foreachneg",
        "foreachnorm",
        "foreachpow",
        "foreachreciprocal",
        "foreachround",
        "foreachrsqrt",
        "foreachsigmoid",
        "foreachsign",
        "foreachsin",
        "foreachsinh",
        "foreachsqrt",
        "foreachsub",
        "foreachtan",
        "foreachtanh",
        "foreachtrunc",
        "foreachzero",
        "fractionalmaxpool2dwithindices",
        "fractionalmaxpool3dwithindices",
        "frobeniusnorm",
        "functionalassertasync",
        "functionalassertscalar",
        "functionalsymconstrainrangeforsize",
        "fusedadagrad",
        "fusedadam",
        "fusedadamw",
        "fuseddropout",
        "fusedmovingavgobsfakequant",
        "fusedmovingavgobsfqhelper",
        "fusedrmsnorm",
        "fusedsdpchoice",
        "fusedsgd",
        "fwprimalcopy",
        "getdevice",
        "getsoftmaxdim",
        "gridsampler",
        "gridsampler2d",
        "gridsampler2dcpufallback",
        "gridsampler3d",
        "groupedmm",
        "gru",
        "grucell",
        "h",
        "handletorchfunction",
        "hascompatibleshallowcopytype",
        "histogramddbinedges",
        "histogramddfrombincts",
        "histogramddfrombintensors",
        "hsmm",
        "indexputimpl",
        "indicescopy",
        "infersize",
        "inprojection",
        "inprojectionpacked",
        "intmm",
        "intrepr",
        "ipu",
        "isalltrue",
        "isanytrue",
        "isdistributed",
        "isneg",
        "ispinned",
        "issamesize",
        "isshared",
        "isview",
        "iszerotensor",
        "lazyclone",
        "linalgcheckerrors",
        "linalgdet",
        "linalgeigh",
        "linalgslogdet",
        "linalgsolveex",
        "linalgsvd",
        "logsoftmaxbackwarddata",
        "lstm",
        "lstmcell",
        "lstmmps",
        "luwithinfo",
        "makedeprecate",
        "makedual",
        "makedualcopy",
        "makeperchannelquantizedtensor",
        "makepertensorquantizedtensor",
        "map2",
        "maskedscale",
        "maskedsoftmax",
        "miopenbatchnorm",
        "miopenconvolution",
        "miopenconvolutionaddrelu",
        "miopenconvolutionrelu",
        "miopenconvolutiontranspose",
        "miopendepthwiseconvolution",
        "miopenrnn",
        "mixeddtypeslinear",
        "mkldnnreshape",
        "mkldnntranspose",
        "mod",
        "mpsconvolution",
        "mpsconvolutiontranspose",
        "mt",
        "mtia",
        "nativebatchnorm",
        "nativebatchnormlegit",
        "nativebatchnormlegitnotraining",
        "nativedropout",
        "nativegroupnorm",
        "nativelayernorm",
        "nativemultiheadattention",
        "nativenorm",
        "negview",
        "negviewcopy",
        "nestedcomputecontiguousstridesoffsets",
        "nestedfrompadded",
        "nestedfrompaddedandnestedexample",
        "nestedfrompaddedtensor",
        "nestedgetjaggeddummy",
        "nestedgetlengths",
        "nestedgetmaxseqlen",
        "nestedgetminseqlen",
        "nestedgetoffsets",
        "nestedgetraggedidx",
        "nestedgetvalues",
        "nestedgetvaluescopy",
        "nestedtensorfrommask",
        "nestedtensorfrommaskleftaligned",
        "nestedtensorfromtensorlist",
        "nestedtensorsize",
        "nestedtensorsoftmaxwithshape",
        "nestedtensorstorageoffsets",
        "nestedtensorstrides",
        "nestedviewfrombuffer",
        "nestedviewfrombuffercopy",
        "nestedviewfromjagged",
        "nestedviewfromjaggedcopy",
        "nnpackavailable",
        "nnpackspatialconvolution",
        "nnz",
        "nogradembeddingrenorm",
        "nogradfill",
        "nogradnormal",
        "nogradtruncnormal",
        "nogradzero",
        "nonlinearitytype",
        "nonzerostatic",
        "normexceptdim",
        "nuclearnorm",
        "op",
        "optional",
        "overload",
        "packpaddedsequence",
        "padpackedsequence",
        "permutecopy",
        "prelukernel",
        "print",
        "propagatexladata",
        "put",
        "qperchannelaxis",
        "qperchannelscales",
        "qperchannelzeropoints",
        "qscale",
        "qscheme",
        "quantizedbatchnorm",
        "quantizedgrucell",
        "quantizedlstmcell",
        "quantizedmaxpool1d",
        "quantizedmaxpool2d",
        "quantizedmaxpool3d",
        "quantizedrnnrelucell",
        "quantizedrnntanhcell",
        "qzeropoint",
        "range",
        "reduceex",
        "registerpostaccumulategradhook",
        "removebatchdim",
        "reshapealiascopy",
        "reshapefromtensor",
        "resizeas",
        "resizeassparse",
        "resizeoutput",
        "reversed",
        "rmsnorm",
        "rnnrelu",
        "rnnrelucell",
        "rnntanh",
        "rnntanhcell",
        "rowindicescopy",
        "rowwiseprune",
        "saddmm",
        "safesoftmax",
        "sampledirichlet",
        "saturateweighttofp16",
        "scaleddotproductattentionmath",
        "scaleddotproductattentionmathformps",
        "scaleddotproductcudnnattention",
        "scaleddotproductefficientattention",
        "scaleddotproductflashattention",
        "scaleddotproductflashattentionforcpu",
        "scaledgroupedmm",
        "scaledmm",
        "segmentreduce",
        "selectcopy",
        "setstate",
        "shapeastensor",
        "slicecopy",
        "sliceinverse",
        "sobolenginedraw",
        "sobolengineff",
        "sobolengineinitializestate",
        "sobolenginescramble",
        "softmaxbackwarddata",
        "sparsebroadcastto",
        "sparsebroadcasttocopy",
        "sparsecootensor",
        "sparsecsrprod",
        "sparsecsrsum",
        "sparsecsrtensor",
        "sparselogsoftmaxbackwarddata",
        "sparsemaskprojection",
        "sparseresize",
        "sparseresizeandclear",
        "sparsesemistructuredaddmm",
        "sparsesemistructuredapply",
        "sparsesemistructuredapplydense",
        "sparsesemistructuredlinear",
        "sparsesemistructuredmm",
        "sparsesemistructuredtile",
        "sparsesoftmaxbackwarddata",
        "sparsesparsematmul",
        "sparsesum",
        "sphericalbesselj0",
        "splitcopy",
        "splitwithsizescopy",
        "spmm",
        "squeezecopy",
        "standardgamma",
        "standardgammagrad",
        "sumtosize",
        "symite",
        "symsqrt",
        "symsum",
        "tcopy",
        "testautogradmultipledispatch",
        "testautogradmultipledispatchview",
        "testautogradmultipledispatchviewcopy",
        "testchecktensor",
        "testfunctorchfallback",
        "testparallelmaterialize",
        "testserializationsubcmul",
        "tocpu",
        "tosparsesemistructured",
        "transformbiasrescaleqkv",
        "transformerencoderlayerfwd",
        "transposecopy",
        "trilinear",
        "tritonmultiheadattention",
        "tritonscaleddotattention",
        "truediv",
        "unbindcopy",
        "unfoldcopy",
        "unique2",
        "unpackdual",
        "unpooloutputsize",
        "unsafeindex",
        "unsafeindexput",
        "unsafemaskedindex",
        "unsafemaskedindexputaccumulate",
        "unsafesplitwithsizes",
        "unsqueezecopy",
        "updatenames",
        "usecudnnctcloss",
        "usecudnnrnnflattenweight",
        "validatecompressedsparseindices",
        "validatesparsebsctensorargs",
        "validatesparsebsrtensorargs",
        "validatesparsecompressedtensorargs",
        "validatesparsecootensorargs",
        "validatesparsecsctensorargs",
        "validatesparsecsrtensorargs",
        "valuescopy",
        "viewcopy",
        "weightint4packmm",
        "weightint4packmmforcpu",
        "weightint4packmmwithscalesandzeros",
        "weightint8packmm",
        "weightnorm",
        "weightnorminterface",
        "wrappedlinearprepack",
        "wrappedquantizedlinearprepacked",
        "xpu",
    }
)

_EXPECTED_KWARGS = {
    "addr": ("input", "vec1", "vec2"),
    "alignas": ("self", "other"),
    "binarycrossentropy": ("input", "target", "weight"),
    "bucketize": ("input", "boundaries"),
    "cdist": ("x1", "x2"),
    "choleskyinverse": ("L",),
    "cov": ("input", "fweights", "aweights"),
    "cumulativetrapezoid": ("y", "x"),
    "diff": ("input", "prepend", "append"),
    "fakequantizeperchannelaffine": ("input", "scale", "zero_point"),
    "fakequantizepertensoraffine": ("input", "scale", "zero_point"),
    "ger": ("input", "vec2"),
    "gumbelsoftmax": ("logits",),
    "hspmm": ("mat1", "mat2"),
    "isin": ("elements", "test_elements"),
    "issetto": ("self", "tensor"),
    "ldlsolve": ("LD", "pivots", "B"),
    "lobpcg": ("A", "B", "X", "iK"),
    "map": ("self", "tensor"),
    "moduleload": ("self", "other"),
    "orgqr": ("input", "tau"),
    "ormqr": ("input", "tau", "other"),
    "pairwisedistance": ("x1", "x2"),
    "quantizeperchannel": ("input", "scales", "zero_points"),
    "quantizepertensor": ("input", "scale", "zero_point"),
    "smm": ("input", "mat"),
    "solveex": ("A", "B"),
    "solvetriangular": ("A", "B"),
    "sspaddmm": ("input", "mat1", "mat2"),
    "svdlowrank": ("A", "M"),
    "tensorsolve": ("A", "B"),
    "trapezoid": ("y", "x"),
    "trapz": ("y", "x"),
    "tripletmarginwithdistanceloss": ("anchor", "positive", "negative"),
    "truncnormal": ("tensor",),
    "unravelindex": ("indices",),
    "vecdot": ("x", "y"),
}


def _decorated_normalized_names() -> set[str]:
    """Return normalized function names from the actual decorated set.

    Returns
    -------
    set[str]
        Normalized names derived from ``ORIG_TORCH_FUNCS``.
    """

    return {_normalize_func_name(func_name.strip("_")) for _, func_name in ORIG_TORCH_FUNCS}


def test_every_decorated_arg_spec_is_static_or_explicitly_unsupported() -> None:
    """Every decorated function has a static spec or a known unsupported entry."""

    decorated_names = _decorated_normalized_names()
    static_names = set(FUNC_ARG_SPECS)
    missing = decorated_names - static_names

    assert missing <= _KNOWN_UNSUPPORTED_ARG_SPECS
    assert _KNOWN_UNSUPPORTED_ARG_SPECS <= decorated_names
    assert not (_KNOWN_UNSUPPORTED_ARG_SPECS & static_names)


def test_high_confidence_static_fills_remain_covered() -> None:
    """High-confidence schema-derived fills must stay in the static table."""

    decorated_names = _decorated_normalized_names()

    assert _HIGH_CONFIDENCE_STATIC_NAMES <= decorated_names
    assert _HIGH_CONFIDENCE_STATIC_NAMES <= set(FUNC_ARG_SPECS)
    assert not (_HIGH_CONFIDENCE_STATIC_NAMES & _KNOWN_UNSUPPORTED_ARG_SPECS)


@pytest.mark.parametrize("func_name,expected_kwargs", sorted(_EXPECTED_KWARGS.items()))
def test_high_confidence_tensor_kwarg_names_match_schema(
    func_name: str, expected_kwargs: tuple[str, ...]
) -> None:
    """Selected static specs must retain their schema-backed tensor kwarg names."""

    spec = FUNC_ARG_SPECS[func_name]

    assert set(expected_kwargs) <= set(spec.tensor_kwargs)


def test_dynamic_fallback_cache_is_self_consistent_for_unlisted_schema() -> None:
    """Tier-3 BFS fallback records observed tensor positions and kwarg names."""

    normalized_name = "torchlenslocalargspeccoverage"
    tensor_arg = torch.randn(2, 3)
    tensor_kwarg = torch.randn(2, 3)
    found_tensors = [tensor_arg, tensor_kwarg]
    found_params: list[torch.nn.Parameter] = []

    _cache_dynamic_spec(
        normalized_name,
        (tensor_arg,),
        {"right": tensor_kwarg},
        found_tensors,
        found_params,
    )
    spec = FUNC_ARG_SPECS.get(normalized_name)
    dynamic_spec = __import__("torchlens")._state._dynamic_arg_specs.pop(normalized_name)

    assert spec is None
    assert dynamic_spec == ArgSpec(positions=(0,), tensor_kwargs=("right",))
