"""GENERATED storage bindings for the declared record schema. DO NOT EDIT.

Regenerate with ``python tools/generate_record_schema.py``; a CI test
(`tests/test_record_schema_bindings.py`) diffs this file against a fresh
generation, so hand edits cannot survive. The declared axes live in
``field_policy.StorageBinding``; classification policy lives in the
generator.
"""

from __future__ import annotations

from .field_policy import StorageBinding, StorageKind

STORAGE_BINDINGS: dict[str, dict[str, StorageBinding]] = {
    "trace": {
        "trace_label": StorageBinding(StorageKind.SCALAR),
        "model_class_name": StorageBinding(StorageKind.SCALAR),
        "model_label": StorageBinding(StorageKind.SCALAR),
        "tlspec_version": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "_tracing_finished": StorageBinding(StorageKind.SCALAR),
        "backend": StorageBinding(StorageKind.SCALAR, annotation="typing.Literal['torch', 'mlx', 'jax', 'tinygrad', 'paddle', 'tf', 'fake'] | str"),
        "backend_runtime_config": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any] | None'),
        "backend_runtime_device_summary": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any] | None'),
        "backend_runtime_version": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "module_identity_mode": StorageBinding(StorageKind.SCALAR, annotation="typing.Literal['torch_module', 'pytree_module', 'function_root', 'object_module']"),
        "param_source": StorageBinding(StorageKind.SCALAR, annotation="typing.Literal['native-module', 'pytree-derived', 'none']"),
        "derived_grads": StorageBinding(StorageKind.SCALAR),
        "capture_mode": StorageBinding(StorageKind.SCALAR),
        "structure_only": StorageBinding(StorageKind.SCALAR),
        "structure_evidence": StorageBinding(StorageKind.SCALAR),
        "intervention_audit": StorageBinding(StorageKind.SCALAR),
        "_runnable": StorageBinding(StorageKind.RUNTIME, annotation="<class 'torchlens._runnable_seam.RunnableTraceState'>"),
        "_fast_run_session": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any | None'),
        "_distributed_plane_p": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any | None'),
        "escape_detector_mode": StorageBinding(StorageKind.RUNTIME),
        "escape_detector_verified": StorageBinding(StorageKind.RUNTIME),
        "escape_diagnostics": StorageBinding(StorageKind.RUNTIME),
        "escape_detector_event_count": StorageBinding(StorageKind.RUNTIME),
        "escape_detector_callback_ns": StorageBinding(StorageKind.RUNTIME),
        "escape_detector_backward_coverage": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_mode": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_verified": StorageBinding(StorageKind.RUNTIME),
        "completeness_diagnostics": StorageBinding(StorageKind.RUNTIME),
        "completeness_decompositions": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_event_count": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_accounted_count": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_expected_opaque_count": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_unaccounted_count": StorageBinding(StorageKind.RUNTIME),
        "completeness_witness_callback_ns": StorageBinding(StorageKind.RUNTIME),
        "capture_verified": StorageBinding(StorageKind.SCALAR),
        "capture_verification_reason": StorageBinding(StorageKind.SCALAR),
        "rescue_rerun": StorageBinding(StorageKind.RUNTIME),
        "capture_owner_thread_id": StorageBinding(StorageKind.RUNTIME),
        "capture_owner_thread_qualified": StorageBinding(StorageKind.RUNTIME),
        "capture_thread_count_start": StorageBinding(StorageKind.RUNTIME),
        "capture_thread_count_end": StorageBinding(StorageKind.RUNTIME),
        "capture_thread_activity_detected": StorageBinding(StorageKind.RUNTIME),
        "capture_guard_passes": StorageBinding(StorageKind.RUNTIME),
        "halted": StorageBinding(StorageKind.SCALAR),
        "halt_reason": StorageBinding(StorageKind.SCALAR),
        "halt_frontier": StorageBinding(StorageKind.SCALAR),
        "_capture_outcome": StorageBinding(StorageKind.SCALAR),
        "_layers_logged": StorageBinding(StorageKind.SCALAR),
        "_layers_saved": StorageBinding(StorageKind.SCALAR),
        "keep_orphans": StorageBinding(StorageKind.SCALAR),
        "intervention_ready": StorageBinding(StorageKind.SCALAR),
        "save_arg_templates": StorageBinding(StorageKind.SCALAR, annotation="<class 'bool'>"),
        "raw_input": StorageBinding(StorageKind.SCALAR),
        "input_preprocessor": StorageBinding(StorageKind.SCALAR, annotation='torchlens.data_classes.trace.ResolvedPreprocessing | None'),
        "_transform": StorageBinding(StorageKind.RUNTIME),
        "transform_repr": StorageBinding(StorageKind.SCALAR),
        "save_raw_input": StorageBinding(StorageKind.SCALAR),
        "batch_render": StorageBinding(StorageKind.SCALAR),
        "raw_output": StorageBinding(StorageKind.SCALAR),
        "decoded_output": StorageBinding(StorageKind.SCALAR),
        "output_postprocessor": StorageBinding(StorageKind.SCALAR, annotation='torchlens.data_classes.trace.ResolvedPostprocessing | None'),
        "output_id2label": StorageBinding(StorageKind.SCALAR, annotation='dict[int, str] | None'),
        "output_num_classes": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "_output_transform": StorageBinding(StorageKind.RUNTIME),
        "save_raw_output": StorageBinding(StorageKind.SCALAR),
        "layer_visualizers": StorageBinding(StorageKind.RUNTIME),
        "save_visualizations": StorageBinding(StorageKind.SCALAR),
        "_visualizer_dir": StorageBinding(StorageKind.RUNTIME),
        "random_seed": StorageBinding(StorageKind.SCALAR),
        "detach_saved_activations": StorageBinding(StorageKind.SCALAR),
        "output_device": StorageBinding(StorageKind.SCALAR),
        "backward_ready": StorageBinding(StorageKind.RUNTIME, annotation="<class 'bool'>"),
        "inference_only": StorageBinding(StorageKind.SCALAR, annotation="<class 'bool'>"),
        "chunked_forward": StorageBinding(StorageKind.SCALAR, annotation="<class 'bool'>"),
        "module_filter": StorageBinding(StorageKind.RUNTIME),
        "emit_nvtx": StorageBinding(StorageKind.SCALAR),
        "raise_on_nan": StorageBinding(StorageKind.SCALAR),
        "annotations": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any]'),
        "observer_spans": StorageBinding(StorageKind.SCALAR),
        "manual_tensor_connections": StorageBinding(StorageKind.SCALAR),
        "forward_source_file": StorageBinding(StorageKind.SCALAR),
        "forward_source_line": StorageBinding(StorageKind.SCALAR),
        "class_source_file": StorageBinding(StorageKind.SCALAR),
        "class_source_line": StorageBinding(StorageKind.SCALAR),
        "init_source_file": StorageBinding(StorageKind.SCALAR),
        "init_source_line": StorageBinding(StorageKind.SCALAR),
        "class_docstring": StorageBinding(StorageKind.COMPUTED),
        "init_signature": StorageBinding(StorageKind.COMPUTED),
        "init_docstring": StorageBinding(StorageKind.COMPUTED),
        "forward_signature": StorageBinding(StorageKind.COMPUTED),
        "forward_docstring": StorageBinding(StorageKind.COMPUTED),
        "code_context": StorageBinding(StorageKind.SCALAR, annotation="list['FuncCallLocation']"),
        "source_snapshots": StorageBinding(StorageKind.SCALAR),
        "capture_cache_hit": StorageBinding(StorageKind.SCALAR),
        "capture_cache_key": StorageBinding(StorageKind.SCALAR),
        "capture_cache_path": StorageBinding(StorageKind.SCALAR),
        "facet_registry_snapshot": StorageBinding(StorageKind.RUNTIME),
        "recording_kept": StorageBinding(StorageKind.SCALAR),
        "_out_dedup_mode": StorageBinding(StorageKind.RUNTIME),
        "_out_identity_cache": StorageBinding(StorageKind.RUNTIME),
        "_out_hash_cache": StorageBinding(StorageKind.RUNTIME),
        "_code_context_cache": StorageBinding(StorageKind.RUNTIME),
        "_replay_arg_version_data_complete": StorageBinding(StorageKind.SCALAR),
        "save_arg_values": StorageBinding(StorageKind.SCALAR),
        "num_context_lines": StorageBinding(StorageKind.SCALAR),
        "save_grads": StorageBinding(StorageKind.SCALAR),
        "capture_tensor_grad_hooks": StorageBinding(StorageKind.SCALAR),
        "_grad_op_nums_to_save": StorageBinding(StorageKind.SCALAR),
        "grad_transform": StorageBinding(StorageKind.RUNTIME),
        "grad_transform_repr": StorageBinding(StorageKind.SCALAR),
        "save_raw_gradients": StorageBinding(StorageKind.SCALAR),
        "save_code_context": StorageBinding(StorageKind.SCALAR),
        "save_rng_states": StorageBinding(StorageKind.SCALAR),
        "recurrence_detection": StorageBinding(StorageKind.SCALAR),
        "grouping": StorageBinding(StorageKind.SCALAR),
        "distributed_scope": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "grouping_policy": StorageBinding(StorageKind.SCALAR),
        "verbose": StorageBinding(StorageKind.SCALAR),
        "profile_enabled": StorageBinding(StorageKind.SCALAR, annotation="<class 'bool'>"),
        "has_gradients": StorageBinding(StorageKind.SCALAR),
        "activation_transform": StorageBinding(StorageKind.RUNTIME),
        "_activation_transform_repr": StorageBinding(StorageKind.SCALAR),
        "save_raw_activations": StorageBinding(StorageKind.SCALAR),
        "save_mode": StorageBinding(StorageKind.SCALAR),
        "input_annotations": StorageBinding(StorageKind.SCALAR),
        "_source_code_blob": StorageBinding(StorageKind.SCALAR),
        "_source_model_ref": StorageBinding(StorageKind.RUNTIME),
        "parent_run": StorageBinding(StorageKind.RUNTIME),
        "model_object_id": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "model_class_qualname": StorageBinding(StorageKind.SCALAR),
        "param_hash_quick": StorageBinding(StorageKind.SCALAR),
        "param_hash_full": StorageBinding(StorageKind.SCALAR),
        "root_entry_point": StorageBinding(StorageKind.SCALAR),
        "input_object_id": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "input_signature_hash": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "mark_layer_depths": StorageBinding(StorageKind.SCALAR),
        "graph_shape_hash": StorageBinding(StorageKind.SCALAR),
        "_intervention_spec": StorageBinding(StorageKind.RUNTIME),
        "state_history": StorageBinding(StorageKind.SCALAR, annotation='list[typing.Any]'),
        "last_run": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any | None'),
        "append_history": StorageBinding(StorageKind.SCALAR),
        "_has_direct_writes": StorageBinding(StorageKind.SCALAR),
        "_warned_direct_write": StorageBinding(StorageKind.RUNTIME),
        "_warned_mutate_in_place": StorageBinding(StorageKind.RUNTIME),
        "_spec_revision": StorageBinding(StorageKind.SCALAR),
        "_out_recipe_revision": StorageBinding(StorageKind.SCALAR),
        "_append_sequence_id": StorageBinding(StorageKind.SCALAR),
        "_last_hook_handle_ids": StorageBinding(StorageKind.RUNTIME),
        "state": StorageBinding(StorageKind.SCALAR, annotation="<enum 'TraceState'>"),
        "is_appended": StorageBinding(StorageKind.SCALAR),
        "relationship_evidence": StorageBinding(StorageKind.SCALAR),
        "replay_frontier": StorageBinding(StorageKind.RUNTIME, annotation='dict[str, torch.Tensor]'),
        "layer_list": StorageBinding(StorageKind.SCALAR),
        "layer_dict_main_keys": StorageBinding(StorageKind.SCALAR),
        "layer_dict_all_keys": StorageBinding(StorageKind.SCALAR),
        "layer_logs": StorageBinding(StorageKind.SCALAR),
        "layer_labels": StorageBinding(StorageKind.EDGE),
        "op_labels": StorageBinding(StorageKind.SCALAR),
        "layer_num_calls": StorageBinding(StorageKind.SCALAR),
        "by_pass": StorageBinding(StorageKind.SCALAR),
        "_layer_nums_to_save": StorageBinding(StorageKind.SCALAR),
        "num_ops": StorageBinding(StorageKind.SCALAR),
        "num_modules": StorageBinding(StorageKind.COMPUTED),
        "_raw_to_final_layer_labels": StorageBinding(StorageKind.SCALAR),
        "_raw_to_final_parent_layer_labels": StorageBinding(StorageKind.SCALAR),
        "_raw_to_final_op_labels": StorageBinding(StorageKind.SCALAR),
        "_final_to_raw_layer_labels": StorageBinding(StorageKind.SCALAR),
        "_lookup_keys_to_layer_num_dict": StorageBinding(StorageKind.SCALAR),
        "_layer_num_to_lookup_keys_dict": StorageBinding(StorageKind.SCALAR),
        "_ambiguous_lookup_keys": StorageBinding(StorageKind.SCALAR),
        "input_layers": StorageBinding(StorageKind.EDGE),
        "output_layers": StorageBinding(StorageKind.EDGE),
        "input_structure": StorageBinding(StorageKind.SCALAR, annotation='typing.Any'),
        "_containers": StorageBinding(StorageKind.SCALAR, annotation='dict[int, typing.Any]'),
        "_annotation_blobs": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any] | None'),
        "buffer_layers": StorageBinding(StorageKind.SCALAR),
        "buffer_num_calls": StorageBinding(StorageKind.SCALAR),
        "_buffer_persistence": StorageBinding(StorageKind.SCALAR),
        "internal_source_ops": StorageBinding(StorageKind.SCALAR),
        "internal_sink_ops": StorageBinding(StorageKind.SCALAR),
        "internally_terminated_bool_ops": StorageBinding(StorageKind.SCALAR),
        "conditional_branch_edges": StorageBinding(StorageKind.SCALAR),
        "conditional_records": StorageBinding(StorageKind.SCALAR),
        "conditional_arm_entry_edges": StorageBinding(StorageKind.SCALAR),
        "conditional_edge_call_indices": StorageBinding(StorageKind.SCALAR),
        "conditionals": StorageBinding(StorageKind.SCALAR),
        "layers_with_params": StorageBinding(StorageKind.SCALAR),
        "op_equivalence_classes": StorageBinding(StorageKind.SCALAR, annotation='dict[str, set[str]]'),
        "_orphan_labels": StorageBinding(StorageKind.SCALAR),
        "_orphan_logs": StorageBinding(StorageKind.SCALAR),
        "orphan_records": StorageBinding(StorageKind.SCALAR),
        "total_activation_memory": StorageBinding(StorageKind.SCALAR),
        "total_gradient_memory": StorageBinding(StorageKind.SCALAR),
        "total_backward_memory": StorageBinding(StorageKind.SCALAR),
        "total_autograd_memory": StorageBinding(StorageKind.SCALAR),
        "num_saved_ops": StorageBinding(StorageKind.SCALAR),
        "saved_activation_memory": StorageBinding(StorageKind.SCALAR),
        "saved_gradient_memory": StorageBinding(StorageKind.SCALAR),
        "num_saved_layers": StorageBinding(StorageKind.SCALAR),
        "num_saved_module_calls": StorageBinding(StorageKind.SCALAR),
        "num_saved_grad_fns": StorageBinding(StorageKind.SCALAR),
        "num_saved_grad_fn_calls": StorageBinding(StorageKind.SCALAR),
        "param_logs": StorageBinding(StorageKind.SCALAR),
        "num_param_tensors": StorageBinding(StorageKind.SCALAR),
        "num_layers_with_params": StorageBinding(StorageKind.SCALAR),
        "num_params": StorageBinding(StorageKind.SCALAR),
        "num_params_trainable": StorageBinding(StorageKind.SCALAR),
        "num_params_frozen": StorageBinding(StorageKind.SCALAR),
        "total_param_memory": StorageBinding(StorageKind.SCALAR),
        "total_param_gradient_memory": StorageBinding(StorageKind.SCALAR),
        "forward_peak_memory": StorageBinding(StorageKind.SCALAR),
        "forward_memory_backend": StorageBinding(StorageKind.SCALAR),
        "capture_start_time": StorageBinding(StorageKind.SCALAR, annotation="<class 'float'>"),
        "capture_end_time": StorageBinding(StorageKind.SCALAR, annotation="<class 'float'>"),
        "_phase_timings": StorageBinding(StorageKind.SCALAR),
        "setup_duration": StorageBinding(StorageKind.SCALAR),
        "forward_duration": StorageBinding(StorageKind.SCALAR),
        "cleanup_duration": StorageBinding(StorageKind.SCALAR),
        "func_calls_duration": StorageBinding(StorageKind.SCALAR),
        "has_backward_pass": StorageBinding(StorageKind.SCALAR),
        "grad_fn_logs": StorageBinding(StorageKind.SCALAR),
        "grad_fn_order": StorageBinding(StorageKind.SCALAR),
        "backward_pass_logs": StorageBinding(StorageKind.SCALAR, annotation='dict[int, torchlens.data_classes.backward_pass.BackwardPass]'),
        "_grad_fn_param_refs": StorageBinding(StorageKind.SCALAR),
        "backward_root_grad_fn_object_ids": StorageBinding(StorageKind.SCALAR, annotation='list[int]'),
        "backward_durations": StorageBinding(StorageKind.SCALAR),
        "num_backward_passes": StorageBinding(StorageKind.SCALAR),
        "backward_peak_memory": StorageBinding(StorageKind.SCALAR),
        "backward_memory_backend": StorageBinding(StorageKind.SCALAR),
        "_cooked_from": StorageBinding(StorageKind.RUNTIME),
        "_capture_phase": StorageBinding(StorageKind.RUNTIME),
        "_settlement_ops_committed": StorageBinding(StorageKind.RUNTIME),
        "_stop_requested": StorageBinding(StorageKind.RUNTIME),
        "_paddle_capture_depth": StorageBinding(StorageKind.RUNTIME),
        "_paddle_op_captures": StorageBinding(StorageKind.RUNTIME),
        "_paddle_alias_annotations": StorageBinding(StorageKind.RUNTIME),
        "_paddle_capture_gap_markers": StorageBinding(StorageKind.RUNTIME),
        "_tf_unresolved_producers": StorageBinding(StorageKind.RUNTIME),
        "_tf_init_op_labels": StorageBinding(StorageKind.RUNTIME),
        "_tf_op_captures": StorageBinding(StorageKind.RUNTIME),
        "_tf_validation_result": StorageBinding(StorageKind.RUNTIME),
        "_tl_save_selector_fire_count": StorageBinding(StorageKind.RUNTIME),
        "_tl_intervene_selector_fire_count": StorageBinding(StorageKind.RUNTIME),
        "_module_call_accessor": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_op_accessor_cache": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_layer_accessor_cache": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_receptive_field_solution": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_rf_directional_solutions": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_optimizer": StorageBinding(StorageKind.RUNTIME),
        "measure_python_peak_memory": StorageBinding(StorageKind.RUNTIME),
        "_forward_peak_memory_pair": StorageBinding(StorageKind.RUNTIME),
        "distributed_witness": StorageBinding(StorageKind.RUNTIME),
        "save_budget": StorageBinding(StorageKind.RUNTIME),
        "track_nonfinite": StorageBinding(StorageKind.RUNTIME),
        "track_device_memory": StorageBinding(StorageKind.RUNTIME),
        "_device_memory_samples": StorageBinding(StorageKind.RUNTIME),
        "grad_fn_timing_provenance": StorageBinding(StorageKind.SCALAR),
        "checkpoint_invocation_witness": StorageBinding(StorageKind.SCALAR),
        "_warned_once": StorageBinding(StorageKind.RUNTIME),
        "_predicate_save_options": StorageBinding(StorageKind.RUNTIME),
        "_predicate_history_size": StorageBinding(StorageKind.RUNTIME),
        "_predicate_history": StorageBinding(StorageKind.RUNTIME),
        "_predicate_lookback": StorageBinding(StorageKind.RUNTIME),
        "_predicate_lookback_payload_policy": StorageBinding(StorageKind.RUNTIME),
        "_capture_config": StorageBinding(StorageKind.RUNTIME),
        "_stop_directive": StorageBinding(StorageKind.RUNTIME),
        "_halt_returns_partial_trace": StorageBinding(StorageKind.RUNTIME),
        "_predicate_save_decisions": StorageBinding(StorageKind.RUNTIME),
        "_predicate_current_contexts": StorageBinding(StorageKind.RUNTIME),
        "_predicate_lookback_candidates": StorageBinding(StorageKind.RUNTIME),
        "_postprocessing_active": StorageBinding(StorageKind.RUNTIME),
        "_raw_transform_escape_detected": StorageBinding(StorageKind.RUNTIME),
        "_raw_dynamo_region_detected": StorageBinding(StorageKind.RUNTIME),
        "_raw_event_shape_hash": StorageBinding(StorageKind.RUNTIME),
        "_output_container_specs_by_raw_label": StorageBinding(StorageKind.RUNTIME),
        "_buffer_accessor": StorageBinding(StorageKind.RUNTIME),
        "_buffer_write_tracker": StorageBinding(StorageKind.RUNTIME),
        "_param_storage_addresses": StorageBinding(StorageKind.RUNTIME),
        "_buffer_initial_values": StorageBinding(StorageKind.SCALAR),
        "_saved_grad_labels": StorageBinding(StorageKind.RUNTIME),
        "ops_with_params": StorageBinding(StorageKind.COMPUTED),
        "_pending_live_fire_records": StorageBinding(StorageKind.RUNTIME),
        "_module_logs": StorageBinding(StorageKind.RUNTIME),
        "_param_logs_by_module": StorageBinding(StorageKind.RUNTIME),
        "_raw_graph_ws": StorageBinding(StorageKind.RUNTIME, annotation="<class 'torchlens.ir.workspaces.RawGraphWorkspace'>"),
        "_module_capture_ws": StorageBinding(StorageKind.RUNTIME, annotation="<class 'torchlens.ir.workspaces.ModuleCaptureWorkspace'>"),
        "_wrapper_runtime_ws": StorageBinding(StorageKind.RUNTIME, annotation="<class 'torchlens.ir.workspaces.WrapperRuntimeWorkspace'>"),
        "_trace_core": StorageBinding(StorageKind.RUNTIME),
        "_primitive_op_profile": StorageBinding(StorageKind.SCALAR, annotation='typing.Any | None'),
        "_pre_forward_rng_states": StorageBinding(StorageKind.RUNTIME),
        "_buffer_storage_addresses": StorageBinding(StorageKind.RUNTIME),
        "_mlx_saved_payloads": StorageBinding(StorageKind.RUNTIME),
        "_mlx_capture_depth": StorageBinding(StorageKind.RUNTIME),
        "_out_writer": StorageBinding(StorageKind.RUNTIME),
        "_save_budget_accountant": StorageBinding(StorageKind.RUNTIME),
        "_keep_outs_in_memory": StorageBinding(StorageKind.RUNTIME),
        "_grad_stream_retain_in_memory": StorageBinding(StorageKind.RUNTIME),
        "_defer_streaming_bundle_finalization": StorageBinding(StorageKind.RUNTIME),
        "_out_sink": StorageBinding(StorageKind.RUNTIME),
        "_orphan_pruned_func_call_ids": StorageBinding(StorageKind.RUNTIME),
        "_capture_parent_edge_truth": StorageBinding(StorageKind.RUNTIME),
        "_nonfinite_capture": StorageBinding(StorageKind.RUNTIME),
        "_autograd_saved_bands": StorageBinding(StorageKind.RUNTIME),
        "_autograd_seen_saved_storages": StorageBinding(StorageKind.RUNTIME),
        "_nonfinite_frontier_out": StorageBinding(StorageKind.RUNTIME),
        "_nonfinite_prefix_finalized": StorageBinding(StorageKind.RUNTIME),
        "_nonfinite_prefix_finalize_error": StorageBinding(StorageKind.RUNTIME),
        "_capture_events": StorageBinding(StorageKind.COMPUTED),
        "_capture_session": StorageBinding(StorageKind.RUNTIME),
        "_tl_backward_hooked_tensor_keys": StorageBinding(StorageKind.RUNTIME),
        "_tl_grad_hook_owner_by_label": StorageBinding(StorageKind.RUNTIME),
        "_tl_rf_probe_active": StorageBinding(StorageKind.RUNTIME, annotation='typing.Any'),
        "_active_backward_pass_index": StorageBinding(StorageKind.RUNTIME),
        "_backward_roots_by_pass": StorageBinding(StorageKind.RUNTIME),
        "_backward_projection_event_count": StorageBinding(StorageKind.RUNTIME),
        "_backward_projection_revision": StorageBinding(StorageKind.RUNTIME),
        "_backward_projection_fold_state": StorageBinding(StorageKind.RUNTIME),
        "_implicit_backward_pass_open": StorageBinding(StorageKind.RUNTIME),
        "_tl_backward_triggers_disarmed": StorageBinding(StorageKind.RUNTIME),
        "_tl_cleaned_up": StorageBinding(StorageKind.RUNTIME),
        "_grad_fn_param_refs_by_object_id": StorageBinding(StorageKind.RUNTIME),
        "_param_log_by_pid": StorageBinding(StorageKind.RUNTIME),
        "_session_param_inventory": StorageBinding(StorageKind.RUNTIME),
        "_session_buffer_inventory": StorageBinding(StorageKind.RUNTIME),
        "_session_buffer_identity": StorageBinding(StorageKind.RUNTIME),
        "_backward_gradfn_refs": StorageBinding(StorageKind.RUNTIME),
        "_tl_predicate_intervention_spec_keys": StorageBinding(StorageKind.RUNTIME),
        "_tl_predicate_intervention_target_keys": StorageBinding(StorageKind.RUNTIME),
        "_tl_injection_state": StorageBinding(StorageKind.RUNTIME),
        "_source_bundle_path": StorageBinding(StorageKind.RUNTIME),
        "_source_bundle_manifest_sha256": StorageBinding(StorageKind.RUNTIME),
        "_retain_layers_to_save_output_parents": StorageBinding(StorageKind.RUNTIME),
        "_rerun_save_request": StorageBinding(StorageKind.RUNTIME),
        "_last_validation_failure": StorageBinding(StorageKind.RUNTIME),
        "_validation_diagnostics": StorageBinding(StorageKind.RUNTIME),
        "_output_style": StorageBinding(StorageKind.RUNTIME),
        "_output_head": StorageBinding(StorageKind.RUNTIME),
        "_output_tokenizer": StorageBinding(StorageKind.RUNTIME),
        "_semantic_output_metadata": StorageBinding(StorageKind.RUNTIME),
    },
    "op": {
        "_label_raw": StorageBinding(StorageKind.INTERNED),
        "_layer_label_raw": StorageBinding(StorageKind.INTERNED),
        "raw_label": StorageBinding(StorageKind.COMPUTED),
        "step_index": StorageBinding(StorageKind.INTERNED),
        "raw_index": StorageBinding(StorageKind.INTERNED),
        "ordinal_index": StorageBinding(StorageKind.INTERNED),
        "source_trace": StorageBinding(StorageKind.COMPUTED),
        "_tracing_finished": StorageBinding(StorageKind.INTERNED),
        "_construction_done": StorageBinding(StorageKind.RUNTIME),
        "label": StorageBinding(StorageKind.INTERNED),
        "label_short": StorageBinding(StorageKind.INTERNED),
        "layer_label": StorageBinding(StorageKind.INTERNED),
        "layer_label_short": StorageBinding(StorageKind.INTERNED),
        "type": StorageBinding(StorageKind.INTERNED),
        "type_index": StorageBinding(StorageKind.INTERNED),
        "pass_index": StorageBinding(StorageKind.INTERNED),
        "num_passes": StorageBinding(StorageKind.INTERNED),
        "lookup_keys": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "out": StorageBinding(StorageKind.PAYLOAD),
        "has_saved_activation": StorageBinding(StorageKind.INTERNED),
        "output_device": StorageBinding(StorageKind.INTERNED),
        "activation_transform": StorageBinding(StorageKind.RUNTIME),
        "annotations": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "interventions": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "intervention_replaced": StorageBinding(StorageKind.INTERNED),
        "detach_saved_activations": StorageBinding(StorageKind.INTERNED),
        "has_saved_args": StorageBinding(StorageKind.INTERNED),
        "saved_args": StorageBinding(StorageKind.PAYLOAD),
        "saved_kwargs": StorageBinding(StorageKind.PAYLOAD),
        "args_template": StorageBinding(StorageKind.RUNTIME),
        "kwargs_template": StorageBinding(StorageKind.RUNTIME),
        "input_ops": StorageBinding(StorageKind.COMPUTED),
        "input_activations": StorageBinding(StorageKind.COMPUTED),
        "input_shapes": StorageBinding(StorageKind.COMPUTED),
        "input_dtypes": StorageBinding(StorageKind.COMPUTED),
        "input_memory": StorageBinding(StorageKind.COMPUTED),
        "num_inputs": StorageBinding(StorageKind.COMPUTED),
        "shape": StorageBinding(StorageKind.INTERNED),
        "transformed_out_shape": StorageBinding(StorageKind.INTERNED),
        "dtype": StorageBinding(StorageKind.INTERNED),
        "dtype_ref": StorageBinding(StorageKind.INTERNED),
        "transformed_out_dtype": StorageBinding(StorageKind.INTERNED),
        "device_ref": StorageBinding(StorageKind.INTERNED),
        "backend_address": StorageBinding(StorageKind.INTERNED),
        "resolver_status": StorageBinding(StorageKind.INTERNED),
        "activation_memory": StorageBinding(StorageKind.INTERNED),
        "transformed_activation_memory": StorageBinding(StorageKind.INTERNED),
        "visualizer_path": StorageBinding(StorageKind.INTERNED),
        "bytes_delta_at_call": StorageBinding(StorageKind.INTERNED),
        "bytes_peak_at_call": StorageBinding(StorageKind.INTERNED),
        "transformed_out": StorageBinding(StorageKind.PAYLOAD),
        "autograd_memory": StorageBinding(StorageKind.INTERNED),
        "num_autograd_tensors": StorageBinding(StorageKind.INTERNED),
        "has_out_variations": StorageBinding(StorageKind.INTERNED),
        "out_versions_by_child": StorageBinding(StorageKind.PAYLOAD),
        "grad": StorageBinding(StorageKind.PAYLOAD),
        "transformed_grad": StorageBinding(StorageKind.PAYLOAD),
        "save_grads": StorageBinding(StorageKind.INTERNED),
        "has_grad": StorageBinding(StorageKind.INTERNED),
        "grad_shape": StorageBinding(StorageKind.INTERNED),
        "transformed_grad_shape": StorageBinding(StorageKind.INTERNED),
        "grad_dtype": StorageBinding(StorageKind.INTERNED),
        "transformed_grad_dtype": StorageBinding(StorageKind.INTERNED),
        "gradient_memory": StorageBinding(StorageKind.INTERNED),
        "transformed_gradient_memory": StorageBinding(StorageKind.INTERNED),
        "func": StorageBinding(StorageKind.RUNTIME),
        "func_id": StorageBinding(StorageKind.INTERNED),
        "func_call_id": StorageBinding(StorageKind.INTERNED),
        "func_name": StorageBinding(StorageKind.INTERNED),
        "func_qualname": StorageBinding(StorageKind.INTERNED),
        "code_context": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "var_names": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "arg_expressions": StorageBinding(StorageKind.COMPUTED),
        "func_duration": StorageBinding(StorageKind.INTERNED),
        "flops_forward": StorageBinding(StorageKind.INTERNED),
        "flops_backward": StorageBinding(StorageKind.INTERNED),
        "func_rng_states": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "func_autocast_state": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "arg_names": StorageBinding(StorageKind.INTERNED),
        "num_args_total": StorageBinding(StorageKind.INTERNED),
        "num_pos_args": StorageBinding(StorageKind.INTERNED),
        "num_kwargs": StorageBinding(StorageKind.INTERNED),
        "non_tensor_pos_args": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "non_tensor_kwargs": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "func_non_tensor_args": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "is_inplace": StorageBinding(StorageKind.INTERNED),
        "grad_fn_class_name": StorageBinding(StorageKind.INTERNED),
        "grad_fn_class_qualname": StorageBinding(StorageKind.INTERNED),
        "grad_fn_object_id": StorageBinding(StorageKind.INTERNED),
        "grad_fn_handle": StorageBinding(StorageKind.RUNTIME),
        "grad_fn": StorageBinding(StorageKind.RUNTIME),
        "in_multi_output": StorageBinding(StorageKind.INTERNED),
        "multi_output_index": StorageBinding(StorageKind.INTERNED),
        "multi_output_name": StorageBinding(StorageKind.INTERNED),
        "container_path": StorageBinding(StorageKind.INTERNED),
        "container_spec": StorageBinding(StorageKind.INTERNED),
        "is_transform": StorageBinding(StorageKind.INTERNED),
        "transform_kind": StorageBinding(StorageKind.INTERNED),
        "transform_chain": StorageBinding(StorageKind.INTERNED),
        "transform_config": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "transform_fn_name": StorageBinding(StorageKind.INTERNED),
        "transform_fn_qualname": StorageBinding(StorageKind.INTERNED),
        "transform_fn_source": StorageBinding(StorageKind.INTERNED),
        "unattributed_tensor_args": StorageBinding(StorageKind.INTERNED),
        "dropped_edge_tensor_args": StorageBinding(StorageKind.INTERNED),
        "parent_params": StorageBinding(StorageKind.EDGE),
        "_param_barcodes": StorageBinding(StorageKind.INTERNED),
        "parent_param_ops": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "_param_logs": StorageBinding(StorageKind.SCALAR),
        "param_shapes": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "num_params": StorageBinding(StorageKind.INTERNED),
        "num_params_trainable": StorageBinding(StorageKind.INTERNED),
        "num_params_frozen": StorageBinding(StorageKind.INTERNED),
        "param_memory": StorageBinding(StorageKind.INTERNED),
        "equivalence_class": StorageBinding(StorageKind.INTERNED),
        "equivalent_ops": StorageBinding(StorageKind.GROUP, mutability="copy_on_read"),
        "recurrent_ops": StorageBinding(StorageKind.GROUP, mutability="copy_on_read"),
        "site_key": StorageBinding(StorageKind.INTERNED),
        "injection_provenance": StorageBinding(StorageKind.SCALAR),
        "episode_step": StorageBinding(StorageKind.INTERNED),
        "tl_authored_root": StorageBinding(StorageKind.INTERNED),
        "parents": StorageBinding(StorageKind.EDGE),
        "parent_arg_positions": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "_edge_uses": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "edge_substitutions": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "edge_replacement_stamps": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "root_ancestors": StorageBinding(StorageKind.BITSET, mutability="mutable_container"),
        "children": StorageBinding(StorageKind.EDGE),
        "has_children": StorageBinding(StorageKind.INTERNED),
        "is_input": StorageBinding(StorageKind.INTERNED),
        "input_was_parameter": StorageBinding(StorageKind.INTERNED),
        "has_input_ancestor": StorageBinding(StorageKind.INTERNED),
        "input_ancestors": StorageBinding(StorageKind.EDGE),
        "min_distance_from_input": StorageBinding(StorageKind.INTERNED),
        "max_distance_from_input": StorageBinding(StorageKind.INTERNED),
        "is_output": StorageBinding(StorageKind.INTERNED),
        "is_output_parent": StorageBinding(StorageKind.INTERNED),
        "is_final_output": StorageBinding(StorageKind.INTERNED),
        "has_output_descendant": StorageBinding(StorageKind.INTERNED),
        "output_descendants": StorageBinding(StorageKind.EDGE),
        "is_orphan": StorageBinding(StorageKind.INTERNED),
        "io_role": StorageBinding(StorageKind.INTERNED),
        "min_distance_to_output": StorageBinding(StorageKind.INTERNED),
        "max_distance_to_output": StorageBinding(StorageKind.INTERNED),
        "is_buffer": StorageBinding(StorageKind.INTERNED),
        "address": StorageBinding(StorageKind.INTERNED),
        "buffer_pass": StorageBinding(StorageKind.INTERNED),
        "buffer_source": StorageBinding(StorageKind.INTERNED),
        "buffer_write_kind": StorageBinding(StorageKind.INTERNED),
        "buffer_value_changed": StorageBinding(StorageKind.INTERNED),
        "buffer_replay_validated": StorageBinding(StorageKind.INTERNED),
        "buffer_source_func_name": StorageBinding(StorageKind.INTERNED),
        "is_internal_source": StorageBinding(StorageKind.INTERNED),
        "is_internally_initialized": StorageBinding(StorageKind.COMPUTED),
        "has_internal_source_ancestor": StorageBinding(StorageKind.INTERNED),
        "internal_source_parents": StorageBinding(StorageKind.INTERNED),
        "internal_source_ancestors": StorageBinding(StorageKind.BITSET, mutability="mutable_container"),
        "is_internal_sink": StorageBinding(StorageKind.INTERNED),
        "is_terminal_bool": StorageBinding(StorageKind.INTERNED),
        "is_terminal_conditional_bool": StorageBinding(StorageKind.INTERNED),
        "conditional_context_kind": StorageBinding(StorageKind.INTERNED),
        "conditional_wrapper_kind": StorageBinding(StorageKind.INTERNED),
        "terminal_conditional_id": StorageBinding(StorageKind.INTERNED),
        "is_scalar_bool": StorageBinding(StorageKind.INTERNED),
        "bool_value": StorageBinding(StorageKind.INTERNED),
        "in_conditionals": StorageBinding(StorageKind.INTERNED),
        "terminal_bool_for": StorageBinding(StorageKind.INTERNED),
        "is_in_conditional_body": StorageBinding(StorageKind.COMPUTED),
        "conditional_branch_stack": StorageBinding(StorageKind.INTERNED),
        "conditional_branch_depth": StorageBinding(StorageKind.INTERNED),
        "conditional_entry_children": StorageBinding(StorageKind.INTERNED),
        "conditional_then_children": StorageBinding(StorageKind.INTERNED),
        "conditional_elif_children": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "conditional_else_children": StorageBinding(StorageKind.INTERNED),
        "conditional_arm_children": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "module": StorageBinding(StorageKind.INTERNED),
        "_address_normalized": StorageBinding(StorageKind.INTERNED),
        "modules": StorageBinding(StorageKind.EDGE),
        "fx_qualpath": StorageBinding(StorageKind.INTERNED),
        "fx_call_index": StorageBinding(StorageKind.INTERNED),
        "module_call_stack": StorageBinding(StorageKind.INTERNED),
        "input_to_module_calls": StorageBinding(StorageKind.INTERNED),
        "module_entry_arg_keys": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "output_of_modules": StorageBinding(StorageKind.EDGE),
        "output_of_module_calls": StorageBinding(StorageKind.EDGE),
        "is_module_output": StorageBinding(StorageKind.INTERNED),
        "is_atomic_module": StorageBinding(StorageKind.INTERNED),
        "atomic_module_call": StorageBinding(StorageKind.INTERNED),
        "func_config": StorageBinding(StorageKind.SCALAR, mutability="mutable_container"),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR),
        "_is_in_conditional_body": StorageBinding(StorageKind.INTERNED),
        "out_ref": StorageBinding(StorageKind.RUNTIME),
        "grad_ref": StorageBinding(StorageKind.RUNTIME),
        "_grad_records": StorageBinding(StorageKind.SCALAR),
        "_receptive_field_cache": StorageBinding(StorageKind.RUNTIME),
        "_projective_field_cache": StorageBinding(StorageKind.RUNTIME),
        "_arg_expressions_cache": StorageBinding(StorageKind.RUNTIME),
        "_pending_blob_id": StorageBinding(StorageKind.RUNTIME),
        "_pending_transformed_out_blob_id": StorageBinding(StorageKind.RUNTIME),
        "_pending_grad_blob_id": StorageBinding(StorageKind.RUNTIME),
        "_pending_transformed_grad_blob_id": StorageBinding(StorageKind.RUNTIME),
        "_facets_cache": StorageBinding(StorageKind.RUNTIME),
    },
    "layer": {
        "layer_label": StorageBinding(StorageKind.SCALAR),
        "layer_label_short": StorageBinding(StorageKind.SCALAR),
        "layer_type": StorageBinding(StorageKind.SCALAR),
        "type_index": StorageBinding(StorageKind.SCALAR),
        "step_index": StorageBinding(StorageKind.SCALAR),
        "ordinal_index": StorageBinding(StorageKind.SCALAR),
        "raw_index": StorageBinding(StorageKind.SCALAR),
        "num_passes": StorageBinding(StorageKind.SCALAR),
        "source_trace": StorageBinding(StorageKind.COMPUTED),
        "func": StorageBinding(StorageKind.RUNTIME),
        "func_name": StorageBinding(StorageKind.SCALAR),
        "func_qualname": StorageBinding(StorageKind.SCALAR),
        "is_inplace": StorageBinding(StorageKind.SCALAR),
        "grad_fn_class_name": StorageBinding(StorageKind.SCALAR),
        "grad_fn_class_qualname": StorageBinding(StorageKind.SCALAR),
        "grad_fn_object_id": StorageBinding(StorageKind.SCALAR),
        "grad_fn_handle": StorageBinding(StorageKind.RUNTIME),
        "grad_fn": StorageBinding(StorageKind.RUNTIME),
        "arg_names": StorageBinding(StorageKind.SCALAR),
        "num_args_total": StorageBinding(StorageKind.SCALAR),
        "num_pos_args": StorageBinding(StorageKind.SCALAR),
        "num_kwargs": StorageBinding(StorageKind.SCALAR),
        "in_multi_output": StorageBinding(StorageKind.SCALAR),
        "multi_output_index": StorageBinding(StorageKind.SCALAR),
        "multi_output_name": StorageBinding(StorageKind.SCALAR),
        "shape": StorageBinding(StorageKind.SCALAR),
        "transformed_out_shape": StorageBinding(StorageKind.SCALAR),
        "dtype": StorageBinding(StorageKind.SCALAR),
        "dtype_ref": StorageBinding(StorageKind.SCALAR),
        "transformed_out_dtype": StorageBinding(StorageKind.SCALAR),
        "device_ref": StorageBinding(StorageKind.SCALAR),
        "backend_address": StorageBinding(StorageKind.SCALAR),
        "resolver_status": StorageBinding(StorageKind.SCALAR),
        "activation_memory": StorageBinding(StorageKind.SCALAR),
        "transformed_activation_memory": StorageBinding(StorageKind.SCALAR),
        "transformed_out": StorageBinding(StorageKind.COMPUTED),
        "autograd_memory": StorageBinding(StorageKind.SCALAR),
        "total_autograd_memory": StorageBinding(StorageKind.SCALAR),
        "num_autograd_tensors": StorageBinding(StorageKind.SCALAR),
        "output_device": StorageBinding(StorageKind.SCALAR),
        "visualizer_path": StorageBinding(StorageKind.SCALAR),
        "activation_transform": StorageBinding(StorageKind.RUNTIME),
        "annotations": StorageBinding(StorageKind.SCALAR),
        "intervention_replaced": StorageBinding(StorageKind.SCALAR),
        "detach_saved_activations": StorageBinding(StorageKind.SCALAR),
        "save_grads": StorageBinding(StorageKind.SCALAR),
        "transformed_grad": StorageBinding(StorageKind.COMPUTED),
        "transformed_grad_shape": StorageBinding(StorageKind.SCALAR),
        "transformed_grad_dtype": StorageBinding(StorageKind.SCALAR),
        "transformed_gradient_memory": StorageBinding(StorageKind.SCALAR),
        "flops_forward": StorageBinding(StorageKind.SCALAR),
        "flops_backward": StorageBinding(StorageKind.SCALAR),
        "_param_barcodes": StorageBinding(StorageKind.SCALAR),
        "_param_logs": StorageBinding(StorageKind.SCALAR),
        "param_shapes": StorageBinding(StorageKind.SCALAR),
        "num_params": StorageBinding(StorageKind.SCALAR),
        "num_params_trainable": StorageBinding(StorageKind.SCALAR),
        "num_params_frozen": StorageBinding(StorageKind.SCALAR),
        "total_param_memory": StorageBinding(StorageKind.SCALAR),
        "equivalence_class": StorageBinding(StorageKind.SCALAR),
        "equivalent_ops": StorageBinding(StorageKind.GROUP, mutability="copy_on_read"),
        "is_input": StorageBinding(StorageKind.SCALAR),
        "input_was_parameter": StorageBinding(StorageKind.SCALAR),
        "is_output": StorageBinding(StorageKind.SCALAR),
        "is_final_output": StorageBinding(StorageKind.SCALAR),
        "is_buffer": StorageBinding(StorageKind.SCALAR),
        "address": StorageBinding(StorageKind.SCALAR),
        "buffer_source": StorageBinding(StorageKind.SCALAR),
        "buffer_write_kind": StorageBinding(StorageKind.SCALAR),
        "buffer_value_changed": StorageBinding(StorageKind.SCALAR),
        "buffer_replay_validated": StorageBinding(StorageKind.SCALAR),
        "buffer_source_func_name": StorageBinding(StorageKind.SCALAR),
        "has_input_ancestor": StorageBinding(StorageKind.SCALAR),
        "io_role": StorageBinding(StorageKind.SCALAR),
        "buffer_pass": StorageBinding(StorageKind.SCALAR),
        "is_internal_source": StorageBinding(StorageKind.SCALAR),
        "is_internal_sink": StorageBinding(StorageKind.SCALAR),
        "is_terminal_bool": StorageBinding(StorageKind.SCALAR),
        "is_scalar_bool": StorageBinding(StorageKind.SCALAR),
        "bool_value": StorageBinding(StorageKind.SCALAR),
        "in_conditionals": StorageBinding(StorageKind.SCALAR),
        "terminal_bool_for": StorageBinding(StorageKind.SCALAR),
        "is_in_conditional_body": StorageBinding(StorageKind.COMPUTED),
        "conditional_role_stacks": StorageBinding(StorageKind.SCALAR),
        "conditional_branch_stack_ops": StorageBinding(StorageKind.SCALAR),
        "conditional_arm_children": StorageBinding(StorageKind.SCALAR),
        "conditional_entry_children": StorageBinding(StorageKind.SCALAR),
        "conditional_then_children": StorageBinding(StorageKind.SCALAR),
        "conditional_elif_children": StorageBinding(StorageKind.SCALAR),
        "conditional_else_children": StorageBinding(StorageKind.SCALAR),
        "module": StorageBinding(StorageKind.SCALAR),
        "modules": StorageBinding(StorageKind.EDGE),
        "output_of_modules": StorageBinding(StorageKind.EDGE),
        "output_of_module_calls": StorageBinding(StorageKind.EDGE),
        "is_atomic_module": StorageBinding(StorageKind.SCALAR),
        "func_config": StorageBinding(StorageKind.SCALAR),
        "ops": StorageBinding(StorageKind.EDGE),
        "call_labels": StorageBinding(StorageKind.SCALAR),
        "_is_in_conditional_body": StorageBinding(StorageKind.SCALAR),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR),
    },
    "module": {
        "address": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "all_addresses": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "has_multiple_addresses": StorageBinding(StorageKind.COMPUTED),
        "name": StorageBinding(StorageKind.COMPUTED),
        "cls": StorageBinding(StorageKind.RUNTIME, annotation='type[typing.Any] | None'),
        "class_name": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "class_qualname": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "class_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "class_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "class_source_location": StorageBinding(StorageKind.COMPUTED),
        "init_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "init_source_location": StorageBinding(StorageKind.COMPUTED),
        "forward_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "forward_source_location": StorageBinding(StorageKind.COMPUTED),
        "class_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_signature": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_signature": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "address_parent": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "address_children": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "address_depth": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "call_parent": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "call_children": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "call_parent_module": StorageBinding(StorageKind.COMPUTED),
        "call_children_modules": StorageBinding(StorageKind.COMPUTED),
        "call_depth": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_calls": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "ops": StorageBinding(StorageKind.EDGE, annotation="<class 'torchlens.data_classes.module.ModuleCallAccessor'>"),
        "call_labels": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "layer_labels": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "layers": StorageBinding(StorageKind.COMPUTED),
        "num_layers": StorageBinding(StorageKind.COMPUTED),
        "input_ops": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "input_layers": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_ops": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_layers": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_structure": StorageBinding(StorageKind.COMPUTED),
        "params": StorageBinding(StorageKind.EDGE, annotation='ParamAccessor'),
        "num_params": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_params_trainable": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_params_frozen": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_param_tensors": StorageBinding(StorageKind.COMPUTED),
        "num_param_tensors_trainable": StorageBinding(StorageKind.COMPUTED),
        "num_param_tensors_frozen": StorageBinding(StorageKind.COMPUTED),
        "recursive_params": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_params": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_params_trainable": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_params_frozen": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_param_tensors": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_param_tensors_trainable": StorageBinding(StorageKind.COMPUTED),
        "num_recursive_param_tensors_frozen": StorageBinding(StorageKind.COMPUTED),
        "recursive_param_addresses": StorageBinding(StorageKind.COMPUTED),
        "param_memory": StorageBinding(StorageKind.COMPUTED),
        "has_trainable_params": StorageBinding(StorageKind.COMPUTED),
        "has_frozen_params": StorageBinding(StorageKind.COMPUTED),
        "buffer_layers": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "training": StorageBinding(StorageKind.SCALAR, annotation="<class 'bool'>"),
        "forward_pre_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "forward_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "backward_pre_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "backward_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "full_backward_pre_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "full_backward_hooks": StorageBinding(StorageKind.SCALAR, annotation='list[torchlens.data_classes.module.HookInfo]'),
        "has_forward_hooks": StorageBinding(StorageKind.COMPUTED),
        "has_backward_hooks": StorageBinding(StorageKind.COMPUTED),
        "forward_args_summary": StorageBinding(StorageKind.COMPUTED),
        "forward_kwargs_summary": StorageBinding(StorageKind.COMPUTED),
        "forward_args_template": StorageBinding(StorageKind.COMPUTED),
        "forward_kwargs_template": StorageBinding(StorageKind.COMPUTED),
        "forward_duration": StorageBinding(StorageKind.COMPUTED),
        "total_forward_duration": StorageBinding(StorageKind.COMPUTED),
        "backward_duration": StorageBinding(StorageKind.COMPUTED),
        "total_backward_duration": StorageBinding(StorageKind.COMPUTED),
        "func_calls_duration": StorageBinding(StorageKind.COMPUTED),
        "total_func_calls_duration": StorageBinding(StorageKind.COMPUTED),
        "total_output_activation_memory": StorageBinding(StorageKind.COMPUTED),
        "total_internal_activation_memory": StorageBinding(StorageKind.COMPUTED),
        "total_output_gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "total_internal_gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "total_autograd_memory": StorageBinding(StorageKind.COMPUTED),
        "num_descendant_calls": StorageBinding(StorageKind.COMPUTED),
        "max_descendant_depth": StorageBinding(StorageKind.COMPUTED),
        "custom_attributes": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any]'),
        "custom_methods": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "_buffer_accessor": StorageBinding(StorageKind.RUNTIME),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR),
        "_facets_cache": StorageBinding(StorageKind.RUNTIME),
    },
    "module_call": {
        "address": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "name": StorageBinding(StorageKind.COMPUTED),
        "all_addresses": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "has_multiple_addresses": StorageBinding(StorageKind.COMPUTED),
        "class_name": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "class_qualname": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "cls": StorageBinding(StorageKind.RUNTIME, annotation='type[typing.Any] | None'),
        "call_index": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "call_label": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "ordinal_index": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "ops": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "num_ops": StorageBinding(StorageKind.COMPUTED),
        "input_ops": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "input_layers": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_ops": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_layers": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "output_structure": StorageBinding(StorageKind.SCALAR, annotation='ContainerSpec | None'),
        "output_paths": StorageBinding(StorageKind.SCALAR, annotation='tuple[tuple[typing.Any, ...], ...]'),
        "forward_arg_names": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "num_forward_args_total": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_forward_pos_args": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "num_forward_kwargs": StorageBinding(StorageKind.SCALAR, annotation="<class 'int'>"),
        "forward_args_summary": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "forward_kwargs_summary": StorageBinding(StorageKind.SCALAR, annotation="<class 'str'>"),
        "forward_args_template": StorageBinding(StorageKind.COMPUTED),
        "forward_kwargs_template": StorageBinding(StorageKind.COMPUTED),
        "forward_args": StorageBinding(StorageKind.SCALAR, annotation='tuple[typing.Any, ...] | None'),
        "forward_kwargs": StorageBinding(StorageKind.SCALAR, annotation='dict[str, typing.Any] | None'),
        "has_saved_forward_args": StorageBinding(StorageKind.COMPUTED),
        "inputs_before_pre_hooks": StorageBinding(StorageKind.SCALAR, annotation='ModuleInputSnapshot | None'),
        "inputs_after_pre_hooks": StorageBinding(StorageKind.SCALAR, annotation='ModuleInputSnapshot | None'),
        "forward_pre_hook_effects": StorageBinding(StorageKind.SCALAR, annotation="tuple['PreHookEffect', ...]"),
        "had_pre_hook_input_change": StorageBinding(StorageKind.COMPUTED),
        "forward_duration": StorageBinding(StorageKind.SCALAR, annotation="<class 'torchlens.quantities.Duration'>"),
        "backward_duration": StorageBinding(StorageKind.COMPUTED),
        "output_activation_memory": StorageBinding(StorageKind.COMPUTED),
        "internal_activation_memory": StorageBinding(StorageKind.COMPUTED),
        "output_gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "internal_gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "autograd_memory": StorageBinding(StorageKind.COMPUTED),
        "param_memory": StorageBinding(StorageKind.COMPUTED),
        "func_calls_duration": StorageBinding(StorageKind.COMPUTED),
        "code_context": StorageBinding(StorageKind.SCALAR, annotation="list['FuncCallLocation']"),
        "module_call_stack": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "call_parent": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "call_children": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "num_descendant_calls": StorageBinding(StorageKind.COMPUTED),
        "max_descendant_depth": StorageBinding(StorageKind.COMPUTED),
        "module": StorageBinding(StorageKind.COMPUTED),
        "num_param_tensors": StorageBinding(StorageKind.COMPUTED),
        "num_param_tensors_trainable": StorageBinding(StorageKind.COMPUTED),
        "num_param_tensors_frozen": StorageBinding(StorageKind.COMPUTED),
        "has_trainable_params": StorageBinding(StorageKind.COMPUTED),
        "has_frozen_params": StorageBinding(StorageKind.COMPUTED),
        "_forward_args_template": StorageBinding(StorageKind.RUNTIME),
        "_forward_kwargs_template": StorageBinding(StorageKind.RUNTIME),
        "_source_trace_strong": StorageBinding(StorageKind.RUNTIME),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR),
        "_facets_cache": StorageBinding(StorageKind.RUNTIME),
    },
    "param": {
        "address": StorageBinding(StorageKind.SCALAR),
        "name": StorageBinding(StorageKind.SCALAR),
        "shape": StorageBinding(StorageKind.SCALAR),
        "dtype": StorageBinding(StorageKind.SCALAR),
        "dtype_ref": StorageBinding(StorageKind.SCALAR),
        "device_ref": StorageBinding(StorageKind.SCALAR),
        "backend_address": StorageBinding(StorageKind.SCALAR),
        "resolver_status": StorageBinding(StorageKind.SCALAR),
        "num_params": StorageBinding(StorageKind.SCALAR),
        "param_memory": StorageBinding(StorageKind.SCALAR),
        "is_trainable": StorageBinding(StorageKind.SCALAR),
        "is_quantized": StorageBinding(StorageKind.COMPUTED),
        "has_optimizer": StorageBinding(StorageKind.SCALAR),
        "module_address": StorageBinding(StorageKind.SCALAR),
        "module_name": StorageBinding(StorageKind.COMPUTED),
        "module_cls": StorageBinding(StorageKind.COMPUTED),
        "all_addresses": StorageBinding(StorageKind.SCALAR),
        "all_module_addresses": StorageBinding(StorageKind.SCALAR),
        "has_multiple_addresses": StorageBinding(StorageKind.COMPUTED),
        "barcode": StorageBinding(StorageKind.SCALAR),
        "num_calls": StorageBinding(StorageKind.SCALAR),
        "used_by_ops": StorageBinding(StorageKind.SCALAR),
        "used_by_layers": StorageBinding(StorageKind.SCALAR),
        "num_uses_by_ops": StorageBinding(StorageKind.COMPUTED),
        "num_uses_by_layers": StorageBinding(StorageKind.COMPUTED),
        "co_parent_params": StorageBinding(StorageKind.SCALAR),
        "has_grad": StorageBinding(StorageKind.COMPUTED),
        "grad_shape": StorageBinding(StorageKind.COMPUTED),
        "grad_dtype": StorageBinding(StorageKind.COMPUTED),
        "gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "_derived_grad_record_path": StorageBinding(StorageKind.SCALAR),
        "_param_ref": StorageBinding(StorageKind.RUNTIME),
        "_param_ref_released": StorageBinding(StorageKind.RUNTIME),
        "_source_trace_ref": StorageBinding(StorageKind.RUNTIME),
        "_lazy_at_prep": StorageBinding(StorageKind.RUNTIME),
        "_has_grad": StorageBinding(StorageKind.SCALAR),
        "_grad_shape": StorageBinding(StorageKind.SCALAR),
        "_grad_dtype": StorageBinding(StorageKind.SCALAR),
        "_grad_memory": StorageBinding(StorageKind.SCALAR),
        "_grad_records": StorageBinding(StorageKind.RUNTIME),
        "_derived_grad_payload": StorageBinding(StorageKind.SCALAR),
    },
    "buffer": {
        "address": StorageBinding(StorageKind.SCALAR),
        "module_address": StorageBinding(StorageKind.SCALAR),
        "name": StorageBinding(StorageKind.COMPUTED),
        "buffer_overwrite_index": StorageBinding(StorageKind.COMPUTED),
        "buffer_pass": StorageBinding(StorageKind.COMPUTED),
        "layer_label": StorageBinding(StorageKind.COMPUTED),
        "call_index": StorageBinding(StorageKind.COMPUTED),
        "versions": StorageBinding(StorageKind.SCALAR),
        "shape": StorageBinding(StorageKind.COMPUTED),
        "dtype": StorageBinding(StorageKind.COMPUTED),
        "initial_value": StorageBinding(StorageKind.COMPUTED),
        "activation_memory": StorageBinding(StorageKind.COMPUTED),
        "has_saved_activation": StorageBinding(StorageKind.COMPUTED),
        "has_grad": StorageBinding(StorageKind.COMPUTED),
        "grad_shape": StorageBinding(StorageKind.COMPUTED),
        "grad_dtype": StorageBinding(StorageKind.COMPUTED),
        "gradient_memory": StorageBinding(StorageKind.COMPUTED),
        "buffer_source": StorageBinding(StorageKind.COMPUTED),
        "module": StorageBinding(StorageKind.COMPUTED),
        "modules": StorageBinding(StorageKind.COMPUTED),
        "_initial_value": StorageBinding(StorageKind.SCALAR),
        "_source_ref": StorageBinding(StorageKind.SCALAR),
    },
    "grad_fn": {
        "grad_fn_object_id": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "class_name": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "class_qualname": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "class_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "class_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "class_source_location": StorageBinding(StorageKind.COMPUTED),
        "class_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "init_source_location": StorageBinding(StorageKind.COMPUTED),
        "init_signature": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "init_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "forward_source_location": StorageBinding(StorageKind.COMPUTED),
        "forward_signature": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "forward_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "backward_source_file": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "backward_source_line": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "backward_source_location": StorageBinding(StorageKind.COMPUTED),
        "backward_signature": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "backward_docstring": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "label": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "type": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "type_index": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "ordinal_index": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "step_index": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "is_custom": StorageBinding(StorageKind.SCALAR, annotation='bool'),
        "order": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "origin_backward_pass": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "creator_object_id": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "differentiates": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "modules": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "module_address": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "module_membership_source": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "has_op": StorageBinding(StorageKind.SCALAR, annotation='bool'),
        "op_label": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "op": StorageBinding(StorageKind.COMPUTED),
        "next_grad_fn_ids": StorageBinding(StorageKind.SCALAR, annotation='list[int]'),
        "parents": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "children": StorageBinding(StorageKind.EDGE, annotation='list[str]'),
        "siblings": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "co_parents": StorageBinding(StorageKind.SCALAR, annotation='list[str]'),
        "has_parents": StorageBinding(StorageKind.COMPUTED),
        "has_children": StorageBinding(StorageKind.COMPUTED),
        "has_siblings": StorageBinding(StorageKind.COMPUTED),
        "has_co_parents": StorageBinding(StorageKind.COMPUTED),
        "calls": StorageBinding(StorageKind.SCALAR, annotation='dict[int, GradFnCall] | GradFnCallAccessor'),
        "num_calls": StorageBinding(StorageKind.COMPUTED),
        "call_labels": StorageBinding(StorageKind.COMPUTED),
        "backward_duration": StorageBinding(StorageKind.COMPUTED),
        "total_backward_duration": StorageBinding(StorageKind.COMPUTED),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR, annotation='Any'),
    },
    "grad_fn_call": {
        "call_index": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "ordinal": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "backward_pass_index": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "call_label": StorageBinding(StorageKind.COMPUTED),
        "backward_duration": StorageBinding(StorageKind.COMPUTED),
        "grad_inputs": StorageBinding(StorageKind.SCALAR, annotation='Any'),
        "grad_outputs": StorageBinding(StorageKind.SCALAR, annotation='Any'),
        "intervention_fire_ref": StorageBinding(StorageKind.SCALAR, annotation='object | None'),
        "timestamp": StorageBinding(StorageKind.SCALAR, annotation='float | None'),
        "_time_started": StorageBinding(StorageKind.SCALAR, annotation='float | None'),
        "_time_finished": StorageBinding(StorageKind.SCALAR, annotation='float | None'),
        "is_saved": StorageBinding(StorageKind.COMPUTED),
        "label": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR, annotation='Any'),
    },
    "backward_pass": {
        "pass_index": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "trigger": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "implicit": StorageBinding(StorageKind.SCALAR, annotation='bool'),
        "outer_context": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "backward_call_context": StorageBinding(StorageKind.SCALAR, annotation='object | None'),
        "root_grad_fn_ids": StorageBinding(StorageKind.SCALAR, annotation='list[int]'),
        "root_meta": StorageBinding(StorageKind.SCALAR, annotation='tuple[object, ...]'),
        "root_grad_arguments": StorageBinding(StorageKind.SCALAR, annotation='object | None'),
        "inputs_subset": StorageBinding(StorageKind.SCALAR, annotation='tuple[object, ...]'),
        "order": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "origin_backward_pass": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "engine_flags": StorageBinding(StorageKind.SCALAR, annotation='dict[str, object] | None'),
        "save_grads_policy": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "duration": StorageBinding(StorageKind.SCALAR, annotation='Duration | None'),
        "peak_memory": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "status": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "order_attribution_coverage": StorageBinding(StorageKind.SCALAR, annotation='float | None'),
        "grad_fn_calls": StorageBinding(StorageKind.SCALAR, annotation='list[Any]'),
        "_source_trace_ref": StorageBinding(StorageKind.SCALAR, annotation='Any'),
    },
    "func_call_location": {
        "file": StorageBinding(StorageKind.SCALAR),
        "line_number": StorageBinding(StorageKind.SCALAR),
        "func_name": StorageBinding(StorageKind.SCALAR),
        "code_firstlineno": StorageBinding(StorageKind.SCALAR),
        "func_qualname": StorageBinding(StorageKind.SCALAR),
        "col_offset": StorageBinding(StorageKind.SCALAR),
        "source_loading_enabled": StorageBinding(StorageKind.SCALAR),
        "func_signature": StorageBinding(StorageKind.COMPUTED),
        "func_docstring": StorageBinding(StorageKind.COMPUTED),
        "call_line": StorageBinding(StorageKind.COMPUTED),
        "code_context": StorageBinding(StorageKind.COMPUTED),
        "source_context": StorageBinding(StorageKind.COMPUTED),
        "code_context_labeled": StorageBinding(StorageKind.COMPUTED),
        "num_context_lines": StorageBinding(StorageKind.COMPUTED),
        "_num_context_lines_requested": StorageBinding(StorageKind.SCALAR),
        "_frame_func_obj": StorageBinding(StorageKind.RUNTIME),
        "_source_loaded": StorageBinding(StorageKind.SCALAR),
        "_code_context": StorageBinding(StorageKind.SCALAR),
        "_source_context": StorageBinding(StorageKind.SCALAR),
        "_code_context_labeled": StorageBinding(StorageKind.SCALAR),
        "_call_line": StorageBinding(StorageKind.SCALAR),
        "_num_context_lines": StorageBinding(StorageKind.SCALAR),
        "_func_signature": StorageBinding(StorageKind.SCALAR),
        "_func_docstring": StorageBinding(StorageKind.SCALAR),
        "_linecache_entry": StorageBinding(StorageKind.RUNTIME),
    },
    "primitive_op": {
        "label": StorageBinding(StorageKind.INTERNED, annotation='str'),
        "sequence": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "capture_phase": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "forward_pass_index": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "backward_epoch_index": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "owner_func_call_id": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "parent_op_refs": StorageBinding(StorageKind.EDGE, annotation='tuple[OpRef, ...]'),
        "parent_grad_fn_call_ref": StorageBinding(StorageKind.SCALAR, annotation='tuple[str, int, int] | None'),
        "owner_status": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "decomposition_slot": StorageBinding(StorageKind.SCALAR, annotation='int'),
        "namespace": StorageBinding(StorageKind.INTERNED, annotation='str'),
        "operator": StorageBinding(StorageKind.INTERNED, annotation='str'),
        "overload": StorageBinding(StorageKind.INTERNED, annotation='str'),
        "schema": StorageBinding(StorageKind.INTERNED, annotation='str | None'),
        "schema_fingerprint": StorageBinding(StorageKind.INTERNED, annotation='str | None'),
        "module_call_stack": StorageBinding(StorageKind.EDGE, annotation='tuple[tuple[str, int], ...]'),
        "input_tensor_facts": StorageBinding(StorageKind.SCALAR, annotation='tuple[Any, ...]'),
        "output_tensor_facts": StorageBinding(StorageKind.SCALAR, annotation='tuple[Any, ...]'),
        "mutation_kind": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "view_copy_kind": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "autocast_context": StorageBinding(StorageKind.INTERNED, annotation='tuple[tuple[str, bool, str], ...]'),
        "dispatch_key_context": StorageBinding(StorageKind.INTERNED, annotation='str | None'),
        "grad_fn_ref": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "grad_fn_link_status": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "grad_fn_link_provenance": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "algorithmic_flops": StorageBinding(StorageKind.SCALAR, annotation='int | None'),
        "flop_status": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "flop_formula_source": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "flop_formula_version": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "outcome": StorageBinding(StorageKind.SCALAR, annotation='str'),
        "exception_type": StorageBinding(StorageKind.SCALAR, annotation='str | None'),
        "execution_context": StorageBinding(StorageKind.INTERNED, annotation='Any'),
    },
}
