"""SURFACE-table machinery: the root surface as machine-readable rows (C01 item 7).

One row per reachable ROOT public name (the ``__all__`` names plus every
lazy-facade namespace), each carrying its home module, implementation layer
(from :mod:`torchlens._architecture`), derived product role, and the
``legacy_top_level`` flag (item 9): bare ``tl.NAME`` is a core-spine claim,
so a root name implemented at L6+ is either a grandfathered legacy row or a
RED gate -- the ban on NEW L6+ root names is immediate, while contraction of
the grandfathered rows waits for the next major.

The FROZEN table lives in ``tests/test_arch_spine_surface_table.tsv`` and is
regenerated by ``tools/generate_surface.py`` (one command; rerun after any
deliberate facade change and review the diff). The lockstep test walks the
live surface both directions against the table, so no generated renderer
(root ``__all__``, budget, badges) can drift from the truth.

Wave-1 scope: the ROOT surface. The full deep reachable walk (every
submodule member) is lane F35's SURFACE-table audit tail; the oracles
harness already owns the reachable-surface walk it will consume.
"""

from __future__ import annotations

from dataclasses import dataclass

from ._architecture import LAYER_ORDER, layer_for_module

__tl_layer__ = "L0"

#: Layer -> derived product role (POWER is rendered, never stored).
_LAYER_ROLES: dict[str, str] = {
    "L0": "core",
    "L1": "core",
    "L2": "core",
    "L3": "core",
    "L4": "core",
    "L5": "core",
    "L6": "appliance",
    "L7": "present",
    "L8": "bridge",
    "L9": "recipe",
}


@dataclass(frozen=True)
class SurfaceRow:
    """One reachable root public name."""

    canonical_path: str
    home_module: str
    implementation_layer: str
    product_role: str
    in_all: bool
    legacy_top_level: bool


def _home_module_for(name: str) -> str:
    """Return the home module of one root facade name WITHOUT resolving it.

    Reads the lazy-attribute table (resolution would import the world and
    the surface walk must stay cold); eager globals fall back to
    ``torchlens``.
    """

    import torchlens

    lazy = getattr(torchlens, "_LAZY_ATTRS", {})
    if name in lazy:
        module_path, attr = lazy[name]
        return module_path
    value = torchlens.__dict__.get(name)
    module = getattr(value, "__module__", None)
    if isinstance(module, str) and module.startswith("torchlens"):
        return module
    return "torchlens"


def surface_rows() -> tuple[SurfaceRow, ...]:
    """Derive the live root-surface rows (the generator and lockstep input)."""

    import torchlens

    lazy = dict(getattr(torchlens, "_LAZY_ATTRS", {}))
    in_all = set(torchlens.__all__)
    public_globals = {
        name
        for name, value in vars(torchlens).items()
        if not name.startswith("_") and (name in in_all or callable(value))
    }
    names = sorted(in_all | set(lazy) | public_globals)
    rows = []
    for name in names:
        home = _home_module_for(name)
        dotted = home[len("torchlens") :].lstrip(".") if home.startswith("torchlens") else home
        layer = layer_for_module(dotted) or "FACADE"
        role = _LAYER_ROLES.get(layer, "facade")
        rows.append(
            SurfaceRow(
                canonical_path=f"torchlens.{name}",
                home_module=home,
                implementation_layer=layer,
                product_role=role,
                in_all=name in in_all,
                legacy_top_level=layer in LAYER_ORDER and LAYER_ORDER[layer] >= LAYER_ORDER["L6"],
            )
        )
    return tuple(rows)


def render_surface_tsv(rows: tuple[SurfaceRow, ...]) -> str:
    """Render rows as the frozen TSV (byte-checked by the lockstep test)."""

    header = (
        "canonical_path\thome_module\timplementation_layer\tproduct_role\tin_all\tlegacy_top_level"
    )
    body = "\n".join(
        f"{row.canonical_path}\t{row.home_module}\t{row.implementation_layer}\t"
        f"{row.product_role}\t{int(row.in_all)}\t{int(row.legacy_top_level)}"
        for row in rows
    )
    return header + "\n" + body + "\n"
