"""Import surface for the planned TorchLens intervention API.

The subpackage exists in Phase 0 only to reserve ownership boundaries and
public import paths. Runtime behavior remains unimplemented and fails closed.
"""

from .bundle import Bundle
from .helpers import (
    bwd_hook,
    clamp,
    gradient_scale,
    gradient_zero,
    mean_ablate,
    noise,
    project_off,
    project_onto,
    resample_ablate,
    scale,
    splice_module,
    steer,
    swap_with,
    zero_ablate,
)
from .hooks import (
    HookContext,
    NormalizedHookEntry,
    make_hook_context,
    normalize_hook,
    normalize_hook_plan,
)
from .replay import replay, replay_from
from .resolver import SiteTable, resolve_sites
from .rerun import rerun
from .runtime import do
from .save import load_intervention_spec, save_intervention
from .selectors import contains, func, in_module, label, module, where
from .errors import InterventionReadyConflictError
from .types import (
    ArgComponent,
    CapturedArgTemplate,
    ContainerSpec,
    DataclassField,
    DictKey,
    EdgeUseRecord,
    FireRecord,
    ForkFieldPolicy,
    FrozenInterventionSpec,
    FrozenTargetSpec,
    FunctionRegistryKey,
    HFKey,
    HelperSpec,
    InterventionSpec,
    LiteralTensor,
    LiteralValue,
    NamedField,
    ParentRef,
    Relationship,
    TargetSpec,
    TensorSliceSpec,
    TupleIndex,
    Unsupported,
)

__all__ = [
    "ArgComponent",
    "Bundle",
    "CapturedArgTemplate",
    "ContainerSpec",
    "DataclassField",
    "DictKey",
    "EdgeUseRecord",
    "FireRecord",
    "ForkFieldPolicy",
    "FrozenInterventionSpec",
    "FrozenTargetSpec",
    "FunctionRegistryKey",
    "HFKey",
    "HelperSpec",
    "HookContext",
    "InterventionSpec",
    "InterventionReadyConflictError",
    "LiteralTensor",
    "LiteralValue",
    "NamedField",
    "Relationship",
    "ParentRef",
    "SiteTable",
    "TargetSpec",
    "TensorSliceSpec",
    "TupleIndex",
    "Unsupported",
    "bwd_hook",
    "clamp",
    "contains",
    "do",
    "func",
    "gradient_scale",
    "gradient_zero",
    "in_module",
    "label",
    "load_intervention_spec",
    "make_hook_context",
    "mean_ablate",
    "module",
    "noise",
    "normalize_hook",
    "normalize_hook_plan",
    "NormalizedHookEntry",
    "project_off",
    "project_onto",
    "replay",
    "replay_from",
    "rerun",
    "resample_ablate",
    "resolve_sites",
    "save_intervention",
    "scale",
    "splice_module",
    "steer",
    "swap_with",
    "where",
    "zero_ablate",
]
