"""Menagerie batch w3a18: LiDAR/camera 3D detection and lane-detection architectures for
autonomous driving.

Sources checked (reference only; no cloning, no pip installs):

  - **Part-A2 Net** ("From Points to Parts: 3D Object Detection from Point Cloud with
    Part-aware and Part-aggregation Network", Shi et al., TPAMI 2020, arXiv:1907.03670).
    Official repo github.com/sshaoshuai/PartA2-Net (readme only; code lives in the
    author's OpenPCDet/PCDet). Two-stage LiDAR detector. **Part-aware stage**: a 3D
    sparse-conv-style (approximated here with a small voxel-grid 3D CNN) U-Net backbone
    predicts, per voxel/point, (a) a foreground/background segmentation score and (b) an
    *intra-object part location* -- the point's position normalized into the [0,1]^3 box
    of its own ground-truth object (e.g. (0,0,0) = one corner of the box, (1,1,1) = the
    opposite corner) -- which is "free" extra supervision derived purely from the 3D box
    label, no extra annotation. The backbone also emits 3D box proposals (anchor-free,
    one proposal per foreground voxel). **RoI-aware point-cloud pooling**: for each
    proposal, the predicted part-locations of the points that fall inside the proposal's
    box are scattered into a small fixed-size 3D grid (RoI-aware pooling groups points by
    a fixed voxel offset within the proposal box, unlike RoI-pooling with a shared
    global max), giving a canonical geometry-aware descriptor per proposal (the pooled
    grid encodes part-location, not just raw features). **Part-aggregation stage**: a
    small 3D CNN + MLP head consumes the pooled part-location grid (plus pooled semantic
    features) to re-score the proposal and refine its box -- i.e. box refinement is driven
    by the *shape* of predicted intra-object part locations, the paper's core novelty.
  - **PersFormer** ("PersFormer: 3D Lane Detection via Perspective Transformer and the
    OpenLane Benchmark", Chen et al., ECCV 2022 Oral, arXiv:2203.11089). Official repo
    github.com/OpenDriveLab/PersFormer_3DLane (`models/PersFormer.py`,
    `models/networks/Lane3D.py::RefPntsGenerator`/`ProjectiveGridGenerator`). The
    distinctive mechanism is the "Perspective Transformer": camera-geometry reference
    points are generated by projecting a regular BEV grid through the known
    image<->ground homography matrix `M` (`RefPntsGenerator`, verified from source --
    `grid = (base_grid_hw3 @ M.T)`, then perspective-divide by the homogeneous coordinate)
    into normalized front-view image coordinates; each BEV query then performs
    deformable cross-attention that samples the front-view feature map at that
    camera-informed reference point plus a handful of *learned offsets* around it
    (bilinear `grid_sample`, softmax-weighted). This directly injects camera geometry
    into the front-view -> BEV feature transform, unlike a plain unconditioned
    cross-attention. PersFormer additionally regresses a unified 2D (front-view) and 3D
    (BEV) lane-anchor pair from shared backbone features and adds a BEV segmentation
    head -- all three (2D head, 3D head, seg head) are kept in the compact reimplementation.
  - **PETRv2** ("PETRv2: A Unified Framework for 3D Perception from Multi-Camera Images",
    Liu et al., ICCV 2023, arXiv:2206.01256; builds on PETR arXiv:2203.05625). Official
    repo github.com/megvii-research/PETR. The distinctive mechanism is "3D position
    embedding" (3D-PE): a frustum of fixed 3D anchor points (one per pixel x per depth
    bin, in the *current* camera's coordinate frame) is generated per image, then
    transformed into the *ego* frame via the camera's known extrinsics; PETRv2's
    temporal extension additionally transforms the **previous** frame's frustum points
    through the known ego-motion transform into the *current* ego frame, giving
    temporally-aligned 3D coordinates for both frames. These 3D coordinates are encoded
    (small MLP) into a 3D-PE tensor per pixel, and PETRv2's "feature-guided position
    encoder" gates the 3D-PE by a sigmoid of the 2D image feature (elementwise) before
    adding it into the image tokens -- unlike PETR's ungated addition. Object queries
    (DETR-style, no reference-point regression) then cross/self-attend over the
    concatenated {current-frame, previous-frame} position-aware tokens from all cameras,
    giving free temporal aggregation via attention alone. PETRv2 also adds BEV
    *segmentation queries*, each responsible for one fixed BEV patch, sharing the same
    decoder. Reimplemented here as: per-camera frustum-PE generation with the ego-frame
    transform for two timesteps (current + previous), feature-guided gating, a shared
    Transformer decoder over concatenated multi-camera multi-timestep tokens, detection
    queries -> box head, and segmentation queries -> per-patch mask head.
  - **PillarNeXt** ("PillarNeXt: Rethinking Network Designs for 3D Object Detection in
    LiDAR Point Clouds", Li et al., CVPR 2023, arXiv:2305.04925). Official repo
    github.com/qcraftai/pillarnext (`det3d/models/necks/aspp.py::ASPPNeck`,
    `det3d/models/readers/pillar_encoder.py::PFNLayer`). Pillar encoding (PointNet-style
    per-pillar MLP + scatter-max over points-in-pillar, standard PointPillars front end,
    already present elsewhere in the catalog) feeds a 2D backbone whose distinctive
    contribution -- verified directly from `aspp.py` -- is the **ASPPNeck**: a *single
    shared* 3x3 conv weight tensor is reused via `F.conv2d(x, weight, dilation=d)` at
    FOUR different dilation rates (1, 6, 12, 18), each producing a different
    receptive field from the identical parameters, plus a parallel 1x1 conv branch and
    the pre-conv identity; all six branches are concatenated (6x channels) and fused by a
    1x1 "post-conv" back to the original width -- a genuine architecture-search finding
    of the paper (reusing one dilated-conv weight across rates, rather than the more
    common per-branch-independent-weight ASPP), contrasted with the plain FPN-style neck
    used by PointPillars/CenterPoint (already in the catalog).
  - **PINet** ("Key Points Estimation and Point Instance Segmentation Approach for Lane
    Detection" / Point Instance Network, Ko et al., IEEE T-ITS 2021, arXiv:2002.06604).
    Official repo github.com/koyeongmin/PINet_new (author repo). The distinctive
    mechanism is a **stacked hourglass** backbone (each hourglass stage supervised, so
    model size can be truncated to fewer stages for weaker hardware) where every stage's
    feature map feeds THREE per-pixel heads: (1) a confidence heatmap of lane keypoints,
    (2) a 2-channel sub-pixel (x, y) offset regression, and (3) a per-pixel embedding
    vector. Lane instances are recovered at inference purely by an *instance-segmentation*
    read of the embeddings -- keypoints whose embeddings are close in embedding space are
    clustered into the same lane, with NO fixed anchors and NO hard-coded max-lane-count
    (the paper's "point instance segmentation" framing). Reimplemented here as a compact
    2-stage stacked-hourglass (encoder-decoder with skip connections) with the three
    per-stage heads kept for both stages (matching the paper's every-stage supervision).
  - **PIXOR** ("PIXOR: Real-Time 3D Object Detection from Point Clouds", Yang, Luo & Urtasun
    (Uber ATG), CVPR 2018, arXiv:1902.06326). No official public code; solid PyTorch
    reimplementation at github.com/philip-huang/PIXOR (also reproduced inside the Det3D
    codebase). The distinctive mechanism (vs. PointPillars/VoxelNet-style detectors,
    already in the catalog) is that PIXOR skips any *learned* per-point/per-pillar
    encoder entirely: raw LiDAR points are rasterized directly into a dense
    hand-crafted birds-eye-view (BEV) pseudo-image by hard height-slicing into discrete
    Z-bins (each channel = binary occupancy of that height slice at that (x, y) cell)
    plus one reflectance/intensity channel -- a fixed, non-learned voxelization, not a
    PointNet. A single-stage fully-convolutional encoder-decoder (with lateral skip
    connections, FPN-style) then predicts, *densely at every BEV pixel* (no anchors,
    no RPN proposals), an objectness score plus a 6-parameter oriented box
    (dx, dy, log(w), log(l), cos(theta), sin(theta)) -- the paper's decoupled
    `cos/sin` orientation regression avoiding angle-wraparound discontinuities.

Random init, CPU, forward-only, small dims for fast tracing.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

# ============================================================
# Part-A2 Net -- part-aware voxel stage + RoI-aware part-location pooling + part-aggregation
# ============================================================


class _VoxelConvBlock(nn.Module):
    """3D-conv-BN-ReLU block (dense small-grid stand-in for sparse 3D convolution)."""

    def __init__(self, in_ch: int, out_ch: int, stride: int = 1) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv3d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False),
            nn.BatchNorm3d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class PartA2Net(nn.Module):
    """Part-A2 Net: part-aware voxel backbone + RoI-aware part-location pooling +
    part-aggregation refinement.

    Stage 1 (part-aware): a small 3D-CNN backbone over a voxelized point cloud predicts
    per-voxel foreground score, intra-object normalized part-location (x, y, z in
    [0, 1]^3 of the voxel's own object box -- "free" supervision from the box label
    alone), and a fixed set of 3D box proposals. Stage 2 (RoI-aware pooling +
    part-aggregation): for each proposal, voxel part-locations within a fixed offset
    grid around the proposal are pooled into a small canonical 3D grid, and a second
    3D-CNN + MLP head re-scores/refines the box from the pooled part-location geometry.
    """

    def __init__(
        self,
        grid: int = 12,
        feat_ch: int = 16,
        n_proposals: int = 8,
        roi_grid: int = 4,
    ) -> None:
        super().__init__()
        self.grid = grid
        self.n_proposals = n_proposals
        self.roi_grid = roi_grid

        # part-aware stage: shared voxel backbone
        self.backbone = nn.Sequential(
            _VoxelConvBlock(1, feat_ch),
            _VoxelConvBlock(feat_ch, feat_ch),
        )
        self.seg_head = nn.Conv3d(feat_ch, 1, 1)  # per-voxel foreground score
        self.part_head = nn.Conv3d(feat_ch, 3, 1)  # per-voxel intra-object part location
        self.proposal_head = nn.Conv3d(feat_ch, 7, 1)  # per-voxel 3D box proposal params

        # fixed proposal-selection projection (stand-in for top-k voxel selection: a
        # learned linear readout from flattened backbone features to n_proposals slots)
        self.proposal_select = nn.Linear(feat_ch * grid**3, n_proposals * 7)

        # part-aggregation stage: small 3D-CNN + MLP over the pooled part-location grid
        self.agg_conv = nn.Sequential(
            _VoxelConvBlock(3 + feat_ch, feat_ch),
            _VoxelConvBlock(feat_ch, feat_ch),
        )
        self.refine_head = nn.Linear(feat_ch * roi_grid**3, 7)  # box refinement per proposal
        self.rescore_head = nn.Linear(feat_ch * roi_grid**3, 1)  # IoU re-score per proposal

    def forward(
        self, voxels: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        b = voxels.shape[0]
        feat = self.backbone(voxels)  # (B, C, G, G, G)
        seg_score = torch.sigmoid(self.seg_head(feat))
        part_loc = torch.sigmoid(self.part_head(feat))  # in [0, 1]^3

        proposals = self.proposal_select(feat.flatten(1)).reshape(b, self.n_proposals, 7)

        # RoI-aware pooling: adaptively pool the (part_loc, feat) volume into a fixed
        # roi_grid^3 canonical grid per proposal (shared pooled volume broadcast across
        # proposals -- a compact stand-in for per-proposal RoI cropping).
        pooled_part = F.adaptive_avg_pool3d(part_loc, self.roi_grid)
        pooled_feat = F.adaptive_avg_pool3d(feat, self.roi_grid)
        pooled = torch.cat([pooled_part, pooled_feat], dim=1)  # (B, 3+C, r, r, r)

        agg = self.agg_conv(pooled).flatten(1)  # (B, C*r^3)
        agg = agg.unsqueeze(1).expand(-1, self.n_proposals, -1)  # broadcast to all proposals
        box_refine = self.refine_head(agg)
        rescore = torch.sigmoid(self.rescore_head(agg)).squeeze(-1)

        refined_boxes = proposals + box_refine
        return seg_score, part_loc, refined_boxes, rescore


def build_part_a2_net() -> nn.Module:
    """Build a small Part-A2 Net two-stage part-aware/part-aggregation detector."""
    return PartA2Net(grid=12, feat_ch=16, n_proposals=8, roi_grid=4).eval()


def example_input_part_a2_net() -> torch.Tensor:
    """Voxelized point cloud occupancy grid (1, 1, 12, 12, 12)."""
    return torch.randn(1, 1, 12, 12, 12)


# ============================================================
# PersFormer -- camera-geometry reference-point deformable perspective transformer
# ============================================================


class _DeformableRefAttention(nn.Module):
    """Deformable cross-attention: samples the source feature map at a per-query
    reference point plus a handful of learned offsets, softmax-pooled.
    """

    def __init__(self, dim: int, n_points: int = 4) -> None:
        super().__init__()
        self.n_points = n_points
        self.offset_head = nn.Linear(dim, n_points * 2)
        self.weight_head = nn.Linear(dim, n_points)
        self.value_proj = nn.Conv2d(dim, dim, 1)
        self.out_proj = nn.Linear(dim, dim)

    def forward(
        self, query: torch.Tensor, ref_pts: torch.Tensor, src_feat: torch.Tensor
    ) -> torch.Tensor:
        # query: (B, N, C); ref_pts: (B, N, 2) in [-1, 1]; src_feat: (B, C, H, W)
        b, n, c = query.shape
        value = self.value_proj(src_feat)  # (B, C, H, W)

        offsets = self.offset_head(query).reshape(b, n, self.n_points, 2) * 0.2
        weights = torch.softmax(self.weight_head(query), dim=-1)  # (B, N, n_points)

        sample_grid = ref_pts.unsqueeze(2) + offsets  # (B, N, n_points, 2)
        sample_grid = sample_grid.reshape(b, n * self.n_points, 1, 2)
        sampled = F.grid_sample(value, sample_grid, align_corners=False)  # (B, C, n*P, 1)
        sampled = sampled.squeeze(-1).transpose(1, 2).reshape(b, n, self.n_points, c)

        pooled = (sampled * weights.unsqueeze(-1)).sum(dim=2)  # (B, N, C)
        return self.out_proj(pooled)


class PersFormer(nn.Module):
    """PersFormer: perspective (homography) reference points + deformable BEV attention.

    A BEV grid of queries is seeded with reference points obtained by projecting the
    BEV ground-plane coordinates through the known image<->ground homography matrix
    (verified from `RefPntsGenerator` in the official source), then each BEV query
    performs deformable cross-attention into the front-view image feature map centered
    on its camera-informed reference point. Shared backbone features additionally feed
    a 2D (front-view) lane head and the transformed BEV features feed both a 3D lane
    head and a BEV segmentation head (the paper's unified 2D/3D + auxiliary-seg design).
    """

    def __init__(self, dim: int = 24, bev_h: int = 8, bev_w: int = 8, n_anchors: int = 6) -> None:
        super().__init__()
        self.dim = dim
        self.bev_h = bev_h
        self.bev_w = bev_w
        self.backbone = nn.Sequential(
            nn.Conv2d(3, dim, 3, stride=2, padding=1),
            nn.BatchNorm2d(dim),
            nn.ReLU(inplace=True),
            nn.Conv2d(dim, dim, 3, stride=2, padding=1),
            nn.BatchNorm2d(dim),
            nn.ReLU(inplace=True),
        )
        self.bev_query_embed = nn.Parameter(torch.randn(1, bev_h * bev_w, dim) * 0.02)
        self.pers_transform = _DeformableRefAttention(dim, n_points=4)
        self.bev_refine = nn.TransformerEncoderLayer(
            dim, nhead=4, dim_feedforward=dim * 2, batch_first=True
        )

        # 2D (front-view) lane anchor head, shared backbone
        self.lane2d_head = nn.Conv2d(dim, n_anchors, 1)
        # 3D (BEV) lane anchor head
        self.lane3d_head = nn.Linear(dim, n_anchors)
        # BEV segmentation head
        self.seg_head = nn.Linear(dim, 1)

    def forward(
        self, image: torch.Tensor, homography: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        b = image.shape[0]
        feat = self.backbone(image)  # (B, C, h, w)

        lane2d = self.lane2d_head(feat)

        # camera-geometry reference points: project the BEV ground-plane grid through
        # the (per-sample) homography matrix, then perspective-divide (verified formula
        # from ProjectiveGridGenerator: grid = (base_grid @ M^T); xy = grid[..., :2] / grid[..., 2:])
        ys, xs = torch.meshgrid(
            torch.linspace(0, 1, self.bev_h), torch.linspace(0, 1, self.bev_w), indexing="ij"
        )
        ones = torch.ones_like(xs)
        base_grid = torch.stack([xs, ys, ones], dim=-1).reshape(self.bev_h * self.bev_w, 3)
        base_grid = base_grid.unsqueeze(0).expand(b, -1, -1)  # (B, N, 3)
        proj = torch.bmm(base_grid, homography.transpose(1, 2))  # (B, N, 3)
        ref_pts = proj[..., :2] / proj[..., 2:3].clamp(min=1e-4)
        ref_pts = (ref_pts - 0.5) * 2  # normalize to [-1, 1] for grid_sample

        bev_query = self.bev_query_embed.expand(b, -1, -1)
        bev_feat = bev_query + self.pers_transform(bev_query, ref_pts, feat)
        bev_feat = self.bev_refine(bev_feat)

        lane3d = self.lane3d_head(bev_feat).mean(dim=1)
        seg = torch.sigmoid(self.seg_head(bev_feat)).reshape(b, self.bev_h, self.bev_w)
        return lane2d, lane3d, seg


def build_persformer() -> nn.Module:
    """Build a small PersFormer perspective-transformer 3D lane detector."""
    return PersFormer(dim=24, bev_h=8, bev_w=8, n_anchors=6).eval()


def example_input_persformer() -> tuple[torch.Tensor, torch.Tensor]:
    """(front-view RGB image (1, 3, 32, 32), 3x3 image<->ground homography matrix)."""
    image = torch.randn(1, 3, 32, 32)
    homography = torch.eye(3).unsqueeze(0) + 0.01 * torch.randn(1, 3, 3)
    return image, homography


# ============================================================
# PETRv2 -- temporally-aligned 3D position embedding + feature-guided gating
# ============================================================


class PETRv2(nn.Module):
    """PETRv2: multi-camera, multi-timestep 3D position-embedding transformer.

    Per-camera, per-timestep frustum points (one per pixel x per depth bin, in that
    camera's local frame) are transformed into the shared ego frame via the camera's
    known extrinsics (current frame) or the composed extrinsics+ego-motion transform
    (previous frame) -- giving temporally-ALIGNED 3D coordinates for both timesteps.
    An MLP encodes these into a 3D position embedding (3D-PE), gated by a sigmoid of
    the 2D image feature (the "feature-guided position encoder") before being added to
    the image tokens. Detection queries and BEV segmentation queries (each responsible
    for one fixed BEV patch) share one Transformer decoder over the concatenated
    {current, previous} x {cameras} position-aware tokens.
    """

    def __init__(
        self,
        dim: int = 24,
        n_cams: int = 2,
        n_depth: int = 4,
        n_det_queries: int = 8,
        n_seg_queries: int = 4,
    ) -> None:
        super().__init__()
        self.dim = dim
        self.n_cams = n_cams
        self.n_depth = n_depth
        self.backbone = nn.Sequential(
            nn.Conv2d(3, dim, 3, stride=2, padding=1),
            nn.BatchNorm2d(dim),
            nn.ReLU(inplace=True),
        )
        self.pe_mlp = nn.Sequential(
            nn.Linear(n_depth * 3, dim), nn.ReLU(inplace=True), nn.Linear(dim, dim)
        )
        self.pe_gate = nn.Conv2d(dim, dim, 1)  # feature-guided gate on the 3D-PE

        self.det_queries = nn.Parameter(torch.randn(1, n_det_queries, dim) * 0.02)
        self.seg_queries = nn.Parameter(torch.randn(1, n_seg_queries, dim) * 0.02)
        self.decoder = nn.TransformerDecoderLayer(
            dim, nhead=4, dim_feedforward=dim * 2, batch_first=True
        )

        self.box_head = nn.Linear(dim, 9)  # (x, y, z, w, l, h, sin, cos, score)
        self.seg_patch_head = nn.Linear(dim, 8 * 8)  # per-query flattened BEV patch mask

    def _frustum_points(self, h: int, w: int, extrinsics: torch.Tensor) -> torch.Tensor:
        """3D frustum anchor points (pixel x depth-bin) transformed into the ego frame."""
        ys, xs = torch.meshgrid(torch.linspace(-1, 1, h), torch.linspace(-1, 1, w), indexing="ij")
        depths = torch.linspace(1.0, 4.0, self.n_depth)
        pix = torch.stack([xs, ys], dim=-1).reshape(h * w, 1, 2).expand(-1, self.n_depth, -1)
        d = depths.reshape(1, self.n_depth, 1).expand(h * w, -1, -1)
        cam_pts = torch.cat([pix * d, d], dim=-1)  # (h*w, n_depth, 3) camera-frame points
        cam_pts = cam_pts.reshape(1, h * w * self.n_depth, 3)
        cam_pts_h = torch.cat([cam_pts, torch.ones_like(cam_pts[..., :1])], dim=-1)  # homogeneous
        ego_pts = torch.einsum(
            "bnk,bck->bnc", cam_pts_h, extrinsics
        )  # apply 4x4-ish transform (B,N,3)
        return ego_pts

    def _encode_camera(self, image: torch.Tensor, extrinsics: torch.Tensor) -> torch.Tensor:
        feat = self.backbone(image)  # (B, C, h, w)
        b, c, h, w = feat.shape
        ego_pts = self._frustum_points(h, w, extrinsics)  # (B, h*w*n_depth, 3)
        ego_pts = ego_pts.reshape(b, h * w, self.n_depth * 3)
        pe = self.pe_mlp(ego_pts)  # (B, h*w, C)
        pe = pe.transpose(1, 2).reshape(b, c, h, w)

        gate = torch.sigmoid(self.pe_gate(feat))  # feature-guided gating of the 3D-PE
        tokens = (feat + gate * pe).flatten(2).transpose(1, 2)  # (B, h*w, C)
        return tokens

    def forward(
        self,
        images_t: torch.Tensor,
        images_t1: torch.Tensor,
        extrinsics_t: torch.Tensor,
        extrinsics_t1: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        b, n_cams = images_t.shape[0], images_t.shape[1]
        tok_t = torch.cat(
            [self._encode_camera(images_t[:, i], extrinsics_t[:, i]) for i in range(n_cams)], dim=1
        )
        tok_t1 = torch.cat(
            [self._encode_camera(images_t1[:, i], extrinsics_t1[:, i]) for i in range(n_cams)],
            dim=1,
        )
        memory = torch.cat([tok_t, tok_t1], dim=1)  # temporal aggregation via attention alone

        det_q = self.det_queries.expand(b, -1, -1)
        seg_q = self.seg_queries.expand(b, -1, -1)
        queries = torch.cat([det_q, seg_q], dim=1)
        decoded = self.decoder(queries, memory)

        n_det = self.det_queries.shape[1]
        det_out = self.box_head(decoded[:, :n_det])
        seg_out = self.seg_patch_head(decoded[:, n_det:])
        return det_out, seg_out


def build_petrv2() -> nn.Module:
    """Build a small PETRv2 multi-camera temporal 3D-PE detector + BEV segmenter."""
    return PETRv2(dim=24, n_cams=2, n_depth=4, n_det_queries=8, n_seg_queries=4).eval()


def example_input_petrv2() -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """(current-frame images, previous-frame images, current extrinsics, previous extrinsics).

    images: (1, n_cams=2, 3, 16, 16); extrinsics: (1, n_cams=2, 3, 4) camera-to-ego transform.
    """
    n_cams = 2
    images_t = torch.randn(1, n_cams, 3, 16, 16)
    images_t1 = torch.randn(1, n_cams, 3, 16, 16)
    extrinsics_t = torch.eye(3, 4).unsqueeze(0).unsqueeze(0).expand(1, n_cams, -1, -1).contiguous()
    extrinsics_t1 = extrinsics_t + 0.01 * torch.randn(1, n_cams, 3, 4)
    return images_t, images_t1, extrinsics_t, extrinsics_t1


# ============================================================
# PillarNeXt -- pillar encoder + shared-weight multi-dilation ASPP neck
# ============================================================


class _PillarEncoder(nn.Module):
    """PointPillars-style per-pillar PointNet: per-point MLP + scatter-max over points-in-pillar."""

    def __init__(self, in_ch: int, out_ch: int) -> None:
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(in_ch, out_ch), nn.BatchNorm1d(out_ch), nn.ReLU(inplace=True)
        )

    def forward(self, points: torch.Tensor) -> torch.Tensor:
        # points: (B, n_pillars, n_pts_per_pillar, in_ch)
        b, p, n, c = points.shape
        feat = self.mlp(points.reshape(b * p * n, c)).reshape(b, p, n, -1)
        pooled, _ = feat.max(dim=2)  # scatter-max over points-in-pillar
        return pooled  # (B, n_pillars, out_ch)


class ASPPNeck(nn.Module):
    """PillarNeXt's ASPP neck: ONE shared 3x3 conv weight reused at four dilation rates
    (1, 6, 12, 18), plus a parallel 1x1 branch and the pre-conv identity, all
    concatenated (6x channels) and fused back down -- verified structure from the
    official `det3d/models/necks/aspp.py::ASPPNeck`.
    """

    def __init__(self, ch: int) -> None:
        super().__init__()
        self.pre_conv = nn.Sequential(
            nn.Conv2d(ch, ch, 3, padding=1, bias=False), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.conv1x1 = nn.Conv2d(ch, ch, 1, bias=False)
        self.shared_weight = nn.Parameter(torch.randn(ch, ch, 3, 3) * 0.02)
        self.post_conv = nn.Sequential(
            nn.Conv2d(ch * 6, ch, 1, bias=False), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pre_conv(x)
        b1x1 = self.conv1x1(x)
        b1 = F.conv2d(x, self.shared_weight, padding=1, dilation=1)
        b6 = F.conv2d(x, self.shared_weight, padding=6, dilation=6)
        b12 = F.conv2d(x, self.shared_weight, padding=12, dilation=12)
        b18 = F.conv2d(x, self.shared_weight, padding=18, dilation=18)
        return self.post_conv(torch.cat([x, b1x1, b1, b6, b12, b18], dim=1))


class PillarNeXt(nn.Module):
    """PillarNeXt: pillar encoder -> scatter to BEV -> sparse-style 2D backbone -> ASPPNeck
    -> CenterPoint-style anchor-free dense head.
    """

    def __init__(self, bev_size: int = 16, ch: int = 16, n_classes: int = 3) -> None:
        super().__init__()
        self.bev_size = bev_size
        self.pillar_encoder = _PillarEncoder(in_ch=6, out_ch=ch)
        self.backbone = nn.Sequential(
            nn.Conv2d(ch, ch, 3, padding=1, stride=1, bias=False),
            nn.BatchNorm2d(ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(ch, ch, 3, padding=1, stride=1, bias=False),
            nn.BatchNorm2d(ch),
            nn.ReLU(inplace=True),
        )
        self.neck = ASPPNeck(ch)
        self.heatmap_head = nn.Conv2d(ch, n_classes, 1)  # anchor-free center heatmap
        self.box_head = nn.Conv2d(ch, 7, 1)

    def forward(
        self, points: torch.Tensor, pillar_coords: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        b = points.shape[0]
        pillar_feat = self.pillar_encoder(points)  # (B, n_pillars, C)
        c = pillar_feat.shape[-1]
        g = self.bev_size

        bev = pillar_feat.new_zeros(b, g * g, c)
        flat_idx = pillar_coords[..., 0] * g + pillar_coords[..., 1]
        bev = bev.scatter_add(1, flat_idx.unsqueeze(-1).expand(-1, -1, c), pillar_feat)
        bev = bev.transpose(1, 2).reshape(b, c, g, g)

        feat = self.backbone(bev)
        feat = self.neck(feat)
        heatmap = torch.sigmoid(self.heatmap_head(feat))
        boxes = self.box_head(feat)
        return heatmap, boxes


def build_pillarnext() -> nn.Module:
    """Build a small PillarNeXt pillar-encoder + ASPP-neck LiDAR detector."""
    return PillarNeXt(bev_size=16, ch=16, n_classes=3).eval()


def example_input_pillarnext() -> tuple[torch.Tensor, torch.Tensor]:
    """(per-pillar points (1, n_pillars=32, n_pts=8, 6), pillar (row, col) BEV coords)."""
    b, n_pillars, n_pts, g = 1, 32, 8, 16
    points = torch.randn(b, n_pillars, n_pts, 6)
    pillar_coords = torch.randint(0, g, (b, n_pillars, 2))
    return points, pillar_coords


# ============================================================
# PINet -- stacked hourglass + per-stage keypoint/offset/embedding instance heads
# ============================================================


class _HourglassStage(nn.Module):
    """Single encoder-decoder hourglass block with a skip connection."""

    def __init__(self, ch: int) -> None:
        super().__init__()
        self.down1 = nn.Sequential(
            nn.Conv2d(ch, ch, 3, stride=2, padding=1), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.down2 = nn.Sequential(
            nn.Conv2d(ch, ch, 3, stride=2, padding=1), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.skip = nn.Sequential(
            nn.Conv2d(ch, ch, 3, padding=1), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.up1 = nn.ConvTranspose2d(ch, ch, 4, stride=2, padding=1)
        self.up2 = nn.ConvTranspose2d(ch, ch, 4, stride=2, padding=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        skip = self.skip(x)
        d = self.down1(x)
        d = self.down2(d)
        u = F.relu(self.up1(d))
        u = self.up2(u)
        return F.relu(u + skip)


class PINet(nn.Module):
    """PINet: stacked hourglass with, at EVERY stage, a keypoint-confidence heatmap head,
    a sub-pixel (x, y) offset head, and an instance-embedding head. Lane instances are
    later recovered by clustering keypoints whose embeddings are close, with no fixed
    anchors -- the "point instance segmentation" mechanism.
    """

    def __init__(self, ch: int = 16, n_stages: int = 2, embed_dim: int = 4) -> None:
        super().__init__()
        self.n_stages = n_stages
        self.stem = nn.Sequential(
            nn.Conv2d(3, ch, 3, padding=1), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.stages = nn.ModuleList([_HourglassStage(ch) for _ in range(n_stages)])
        self.conf_heads = nn.ModuleList([nn.Conv2d(ch, 1, 1) for _ in range(n_stages)])
        self.offset_heads = nn.ModuleList([nn.Conv2d(ch, 2, 1) for _ in range(n_stages)])
        self.embed_heads = nn.ModuleList([nn.Conv2d(ch, embed_dim, 1) for _ in range(n_stages)])

    def forward(
        self, image: torch.Tensor
    ) -> tuple[list[torch.Tensor], list[torch.Tensor], list[torch.Tensor]]:
        feat = self.stem(image)
        confs, offsets, embeds = [], [], []
        for stage, conf_h, off_h, emb_h in zip(
            self.stages, self.conf_heads, self.offset_heads, self.embed_heads
        ):
            feat = stage(feat)
            confs.append(torch.sigmoid(conf_h(feat)))
            offsets.append(torch.tanh(off_h(feat)))
            embeds.append(emb_h(feat))
        return confs, offsets, embeds


def build_pinet() -> nn.Module:
    """Build a small 2-stage stacked-hourglass PINet lane keypoint/instance detector."""
    return PINet(ch=16, n_stages=2, embed_dim=4).eval()


def example_input_pinet() -> torch.Tensor:
    """Single road-scene RGB image (1, 3, 32, 32)."""
    return torch.randn(1, 3, 32, 32)


# ============================================================
# PIXOR -- fixed height-sliced BEV rasterization + dense oriented-box head
# ============================================================


class PIXOR(nn.Module):
    """PIXOR: dense BEV pseudo-image (fixed height-slice occupancy, no learned point
    encoder) -> single-stage fully-convolutional encoder-decoder with lateral skips ->
    dense per-pixel objectness + decoupled (cos, sin) oriented-box regression.
    """

    def __init__(self, in_ch: int = 5, ch: int = 16) -> None:
        super().__init__()
        # in_ch = n_height_bins (occupancy) + 1 (reflectance), a FIXED (non-learned)
        # BEV rasterization -- no PointNet/pillar encoder, unlike PointPillars.
        self.stem = nn.Sequential(
            nn.Conv2d(in_ch, ch, 3, padding=1), nn.BatchNorm2d(ch), nn.ReLU(inplace=True)
        )
        self.enc1 = nn.Sequential(
            nn.Conv2d(ch, ch * 2, 3, stride=2, padding=1),
            nn.BatchNorm2d(ch * 2),
            nn.ReLU(inplace=True),
        )
        self.enc2 = nn.Sequential(
            nn.Conv2d(ch * 2, ch * 4, 3, stride=2, padding=1),
            nn.BatchNorm2d(ch * 4),
            nn.ReLU(inplace=True),
        )
        self.up1 = nn.ConvTranspose2d(ch * 4, ch * 2, 4, stride=2, padding=1)
        self.lat1 = nn.Conv2d(ch * 2, ch * 2, 1)  # lateral (FPN-style) skip fusion
        self.up2 = nn.ConvTranspose2d(ch * 2, ch, 4, stride=2, padding=1)
        self.lat2 = nn.Conv2d(ch, ch, 1)
        self.objectness_head = nn.Conv2d(ch, 1, 1)
        # decoupled oriented-box regression: (dx, dy, log_w, log_l, cos, sin)
        self.box_head = nn.Conv2d(ch, 6, 1)

    def forward(self, bev_image: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        s = self.stem(bev_image)
        e1 = self.enc1(s)
        e2 = self.enc2(e1)
        d1 = F.relu(self.up1(e2) + self.lat1(e1))
        d2 = F.relu(self.up2(d1) + self.lat2(s))
        objectness = torch.sigmoid(self.objectness_head(d2))
        boxes = self.box_head(d2)
        return objectness, boxes


def build_pixor() -> nn.Module:
    """Build a small PIXOR fixed-rasterization dense BEV 3D detector."""
    return PIXOR(in_ch=5, ch=16).eval()


def example_input_pixor() -> torch.Tensor:
    """Fixed height-sliced BEV pseudo-image (1, 5=4 height bins + 1 reflectance, 32, 32)."""
    return torch.randn(1, 5, 32, 32)


MENAGERIE_ENTRIES = [
    ("Part-A2 Net", "build_part_a2_net", "example_input_part_a2_net", "2020", "VIS"),
    ("PersFormer", "build_persformer", "example_input_persformer", "2022", "VIS"),
    ("PETRv2", "build_petrv2", "example_input_petrv2", "2023", "VIS"),
    ("PillarNeXt", "build_pillarnext", "example_input_pillarnext", "2023", "VIS"),
    ("PINet", "build_pinet", "example_input_pinet", "2021", "VIS"),
    ("PIXOR", "build_pixor", "example_input_pixor", "2018", "VIS"),
]
