# FAITHFUL PORT of NVlabs/tiny-cuda-nn @ master + USharma002/py-neural-path-guiding @ main
# (original framework: C++/CUDA custom kernels via the `tinycudann` PyTorch extension)
#
# "Real-time Neural Radiance Caching for Path Tracing" (Muller, Rousselle, Novak, Keller;
# SIGGRAPH 2021 / ACM TOG). NVIDIA's own NRC library releases (NVIDIA-RTX/NRC) and the
# reference `tinycudann` bindings (bindings/torch/tinycudann/modules.py) both hard-require
# a compiled custom-CUDA extension (`tinycudann_bindings`) built for the local GPU compute
# capability -- `tinycudann/__init__.py` raises `EnvironmentError` at import time if that
# extension is missing, so it cannot be installed/vendored/run in this base env (no compiler
# toolchain, no per-arch prebuilt wheels on PyPI). A real, public, pure-Python *usage* of
# NRC exists at USharma002/py-neural-path-guiding (networks/nrc.py, class
# `NeuralRadianceCache`) -- it wires up a `tcnn.NetworkWithInputEncoding` with the exact
# encoding/network config transcribed below (Composite[HashGrid, SphericalHarmonics x2,
# OneBlob] -> FullyFusedMLP), but it still imports `tinycudann` directly and thus hits the
# same hard CUDA-extension wall. Per the FAITHFUL PORT rung, we transcribe the actual
# encoding math and network shape from the real tiny-cuda-nn CUDA source (each op below is
# a direct translation, not a guess from the paper):
#   - `include/tiny-cuda-nn/encodings/grid.h` (HashGrid): per-level N-linear interpolation
#     over either a dense or a spatially-hashed feature grid; grid_index/grid_scale exactly
#     as in `common_device.h` (default HashType::CoherentPrime lcg_hash with the real prime
#     factor table).
#   - `include/tiny-cuda-nn/common_device.h`'s `sh_enc` (SphericalHarmonicsEncoding):
#     real-valued spherical-harmonic basis polynomials up to degree 4 (16 outputs),
#     verbatim closed-form coefficients from the CUDA source (generated by NVIDIA's own
#     scripts/gen_sh.py from the Sloan SH recurrence relations).
#   - `include/tiny-cuda-nn/encodings/oneblob.h` (OneBlobEncoding): per-scalar quartic-CDF
#     soft-binning (`quartic_cdf`), verbatim from `common_device.h`.
#   - `include/tiny-cuda-nn/networks/fully_fused_mlp.h`: architecturally a uniform-width
#     `n_hidden_layers`-deep MLP with a fixed activation/output_activation (`FullyFusedMLP`
#     is a CUDA kernel-fusion optimization of exactly this MLP topology, not a distinct
#     architecture -- the tcnn docs describe it as such); reproduced here as plain
#     `nn.Linear` + `nn.ReLU` layers matching n_neurons=64, n_hidden_layers=4 from the real
#     `nrc.py` config, output_activation="None".
# The wrapping module (`NeuralRadianceCache`: bbox-normalize position -> pack
# pos/view/normal/roughness -> encode -> FullyFusedMLP -> softplus) mirrors
# `py-neural-path-guiding`'s `networks/nrc.py` forward/query pipeline verbatim, with the
# `tcnn.NetworkWithInputEncoding` call replaced by the torch modules below.
import math

import torch
import torch.nn as nn
import torch.nn.functional as F

MENAGERIE_ZOO = "ported-pytorch"


# ---- ported from include/tiny-cuda-nn/common_device.h (grid_hash: HashType::CoherentPrime) ----
_COHERENT_PRIME_FACTORS = (1, 2654435761, 805459861, 3674653429, 2097192037, 1434869437, 2165219737)
_UINT32_MASK = 0xFFFFFFFF


def _lcg_hash_3d(gx: torch.Tensor, gy: torch.Tensor, gz: torch.Tensor) -> torch.Tensor:
    """Verbatim port of common_device.h::lcg_hash<3> with HashType::CoherentPrime factors."""
    p0, p1, p2 = _COHERENT_PRIME_FACTORS[0], _COHERENT_PRIME_FACTORS[1], _COHERENT_PRIME_FACTORS[2]
    gx = gx.to(torch.int64)
    gy = gy.to(torch.int64)
    gz = gz.to(torch.int64)
    h = ((gx * p0) & _UINT32_MASK) ^ ((gy * p1) & _UINT32_MASK) ^ ((gz * p2) & _UINT32_MASK)
    return h & _UINT32_MASK


class HashGridEncoding(nn.Module):
    """Port of include/tiny-cuda-nn/encodings/grid.h (GridType::Hash, N_POS_DIMS=3,
    N-linear interpolation, HashType::CoherentPrime), for 3D inputs in [0, 1]^3.
    """

    def __init__(
        self,
        n_levels=16,
        n_features_per_level=2,
        log2_hashmap_size=19,
        base_resolution=16,
        per_level_scale=1.5,
    ):
        super().__init__()
        self.n_levels = n_levels
        self.n_features_per_level = n_features_per_level
        self.hashmap_size = 1 << log2_hashmap_size
        self.base_resolution = base_resolution
        self.per_level_scale = per_level_scale
        # One [hashmap_size, F] table of learnable features per level (grid.h's `grid` param
        # tensor, sliced per level via an offset table in the real code; here materialized
        # as one Parameter per level for clarity, matching the same total memory layout).
        self.levels = nn.ParameterList(
            [
                nn.Parameter(
                    torch.zeros(self.hashmap_size, n_features_per_level).uniform_(-1e-4, 1e-4)
                )
                for _ in range(n_levels)
            ]
        )

    @property
    def n_output_dims(self):
        return self.n_levels * self.n_features_per_level

    def _grid_scale(self, level: int) -> float:
        # grid_scale(): exp2(level * log2(per_level_scale)) * base_resolution - 1
        return (self.per_level_scale**level) * self.base_resolution - 1.0

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        N = x.shape[0]
        outs = []
        for level in range(self.n_levels):
            scale = self._grid_scale(level)
            resolution = int(math.ceil(scale)) + 1
            pos = x * scale
            pos_grid = torch.floor(pos)
            frac = pos - pos_grid  # per-dim interpolation weight

            # N-linear interpolation over the (up to) 8 corners of the surrounding cell.
            level_out = torch.zeros(N, self.n_features_per_level, dtype=x.dtype, device=x.device)
            for corner in range(8):
                weight = torch.ones(N, dtype=x.dtype, device=x.device)
                gx = pos_grid[:, 0]
                gy = pos_grid[:, 1]
                gz = pos_grid[:, 2]
                if corner & 1:
                    weight = weight * frac[:, 0]
                    gx = gx + 1
                else:
                    weight = weight * (1 - frac[:, 0])
                if corner & 2:
                    weight = weight * frac[:, 1]
                    gy = gy + 1
                else:
                    weight = weight * (1 - frac[:, 1])
                if corner & 4:
                    weight = weight * frac[:, 2]
                    gz = gz + 1
                else:
                    weight = weight * (1 - frac[:, 2])

                # grid_index(): dense linear index if resolution^3 fits in hashmap_size,
                # else spatial hash (matches grid.h's MAX_BASES[3]=0x659=1625 gate).
                if resolution <= 0x659 and (resolution**3) < self.hashmap_size:
                    idx = (gx + gy * resolution + gz * resolution * resolution).to(
                        torch.int64
                    ) % self.hashmap_size
                else:
                    idx = _lcg_hash_3d(gx, gy, gz) % self.hashmap_size
                level_out = level_out + weight.unsqueeze(-1) * self.levels[level][idx]
            outs.append(level_out)
        return torch.cat(outs, dim=-1)


# ---- ported from include/tiny-cuda-nn/common_device.h::sh_enc (degree=4, 16 outputs) ----
class SphericalHarmonicsEncoding(nn.Module):
    """Port of SphericalHarmonicsEncoding (encodings/spherical_harmonics.h), degree=4.
    Input is a 3D direction in [0, 1]^3 (matching tcnn's own [0,1]->[-1,1] convention,
    applied via `x = data_in * 2 - 1` exactly as in `kernel_sh`).
    """

    def __init__(self, degree=4):
        super().__init__()
        assert 1 <= degree <= 4, "this port only reproduces up to the degree used by nrc.py"
        self.degree = degree

    @property
    def n_output_dims(self):
        return self.degree * self.degree

    def forward(self, d: torch.Tensor) -> torch.Tensor:
        d = d * 2.0 - 1.0
        x, y, z = d[:, 0], d[:, 1], d[:, 2]
        xy, xz, yz = x * y, x * z, y * z
        x2, y2, z2 = x * x, y * y, z * z

        out = [0.28209479177387814 * torch.ones_like(x)]
        if self.degree > 1:
            out += [
                -0.48860251190291987 * y,
                0.48860251190291987 * z,
                -0.48860251190291987 * x,
            ]
        if self.degree > 2:
            out += [
                1.0925484305920792 * xy,
                -1.0925484305920792 * yz,
                0.94617469575755997 * z2 - 0.31539156525251999,
                -1.0925484305920792 * xz,
                0.54627421529603959 * x2 - 0.54627421529603959 * y2,
            ]
        if self.degree > 3:
            out += [
                0.59004358992664352 * y * (-3.0 * x2 + y2),
                2.8906114426405538 * xy * z,
                0.45704579946446572 * y * (1.0 - 5.0 * z2),
                0.3731763325901154 * z * (5.0 * z2 - 3.0),
                0.45704579946446572 * x * (1.0 - 5.0 * z2),
                1.4453057213202769 * z * (x2 - y2),
                0.59004358992664352 * x * (-x2 + 3.0 * y2),
            ]
        return torch.stack(out, dim=-1)


# ---- ported from include/tiny-cuda-nn/encodings/oneblob.h + common_device.h::quartic_cdf ----
def _quartic_cdf(x: torch.Tensor, inv_radius: float) -> torch.Tensor:
    u = x * inv_radius
    u2 = u * u
    u4 = u2 * u2
    val = (15.0 / 16.0) * u * (1 - (2.0 / 3.0) * u2 + (1.0 / 5.0) * u4) + 0.5
    return torch.clamp(val, 0.0, 1.0)


class OneBlobEncoding(nn.Module):
    """Port of OneBlobEncoding (encodings/oneblob.h): per-scalar wraparound quartic-CDF
    soft one-hot binning into `n_bins` bins.
    """

    def __init__(self, n_bins=4):
        super().__init__()
        self.n_bins = n_bins

    @property
    def n_output_dims(self):
        return self.n_bins

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (N, 1)
        N = x.shape[0]
        bin_idx = (
            torch.arange(self.n_bins, device=x.device, dtype=x.dtype).unsqueeze(0).expand(N, -1)
        )
        left_boundary = bin_idx / self.n_bins
        xv = x.expand(-1, self.n_bins)
        left_cdf = (
            _quartic_cdf(left_boundary - xv, self.n_bins)
            + _quartic_cdf(left_boundary - xv - 1.0, self.n_bins)
            + _quartic_cdf(left_boundary - xv + 1.0, self.n_bins)
        )
        # wraparound: right_cdf of bin i == left_cdf of bin (i+1 mod n_bins), +1 at the wrap
        right_cdf = torch.roll(left_cdf, shifts=-1, dims=1)
        right_cdf = right_cdf.clone()
        right_cdf[:, -1] = right_cdf[:, -1] + 1.0
        return right_cdf - left_cdf


class CompositeEncoding(nn.Module):
    """Port of encodings/composite.h: concatenate the outputs of independently-configured
    sub-encodings applied to disjoint slices of the input, exactly matching nrc.py's
    `config["encoding"]["nested"]` list (pos(3)->HashGrid, view(3)->SH, normal(3)->SH,
    roughness(1)->OneBlob).
    """

    def __init__(self):
        super().__init__()
        self.pos_enc = HashGridEncoding(
            n_levels=16,
            n_features_per_level=2,
            log2_hashmap_size=19,
            base_resolution=16,
            per_level_scale=1.5,
        )
        self.view_enc = SphericalHarmonicsEncoding(degree=4)
        self.normal_enc = SphericalHarmonicsEncoding(degree=4)
        self.rough_enc = OneBlobEncoding(n_bins=4)

    @property
    def n_output_dims(self):
        return (
            self.pos_enc.n_output_dims
            + self.view_enc.n_output_dims
            + self.normal_enc.n_output_dims
            + self.rough_enc.n_output_dims
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        pos, view, normal, rough = x[:, 0:3], x[:, 3:6], x[:, 6:9], x[:, 9:10]
        return torch.cat(
            [
                self.pos_enc(pos),
                self.view_enc(view),
                self.normal_enc(normal),
                self.rough_enc(rough),
            ],
            dim=-1,
        )


class FullyFusedMLPPort(nn.Module):
    """Architectural port of networks/fully_fused_mlp.h: a uniform-width MLP with
    n_hidden_layers hidden layers of n_neurons units, ReLU activation, linear output.
    ("Fully fused" refers to the CUDA kernel-fusion implementation strategy, not a
    distinct network topology -- the tcnn docs describe FullyFusedMLP as a fast, fused
    implementation of exactly this feedforward MLP shape.)
    """

    def __init__(self, n_input_dims, n_output_dims, n_neurons=64, n_hidden_layers=4):
        super().__init__()
        layers = [nn.Linear(n_input_dims, n_neurons), nn.ReLU()]
        for _ in range(n_hidden_layers - 1):
            layers += [nn.Linear(n_neurons, n_neurons), nn.ReLU()]
        layers += [nn.Linear(n_neurons, n_output_dims)]  # output_activation="None"
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class NeuralRadianceCache(nn.Module):
    """Port of USharma002/py-neural-path-guiding networks/nrc.py::NeuralRadianceCache
    forward path: pack (pos, view_dir, normal, roughness) -> CompositeEncoding ->
    FullyFusedMLP -> softplus (forced-positive radiance output).
    """

    def __init__(self):
        super().__init__()
        self.encoding = CompositeEncoding()
        self.model = FullyFusedMLPPort(
            n_input_dims=self.encoding.n_output_dims,
            n_output_dims=3,
            n_neurons=64,
            n_hidden_layers=4,
        )

    @staticmethod
    def _unit(x: torch.Tensor) -> torch.Tensor:
        return F.normalize(x, dim=-1)

    def forward(
        self,
        pos_01: torch.Tensor,
        view_dirs: torch.Tensor,
        normals: torch.Tensor,
        roughness: torch.Tensor,
    ) -> torch.Tensor:
        view_dirs = self._unit(view_dirs)
        normals = self._unit(normals)
        if roughness.ndim == 1:
            roughness = roughness.unsqueeze(1)
        x = torch.cat([pos_01, view_dirs, normals, roughness], dim=1)
        y = self.encoding(x)
        y = self.model(y)
        return F.softplus(y)


# ---- staging build/example helpers ----
def build_neural_radiance_cache():
    torch.manual_seed(0)
    return NeuralRadianceCache()


def example_input_neural_radiance_cache():
    torch.manual_seed(0)
    pos_01 = torch.rand(8, 3)
    view_dirs = torch.randn(8, 3)
    normals = torch.randn(8, 3)
    roughness = torch.rand(8, 1)
    return (pos_01, view_dirs, normals, roughness)


MENAGERIE_ENTRIES = [
    (
        "NeuralRadianceCache-NRC",
        build_neural_radiance_cache,
        example_input_neural_radiance_cache,
        2021,
        "ported-pytorch",
    ),
]
