# SOURCE: vendored from https://github.com/mahmoodlab/HIPT @ master
# (1-Hierarchical-Pretraining/vision_transformer.py, HIPT_4K/vision_transformer4k.py,
#  HIPT_4K/hipt_4k.py)
# HIPT: Hierarchical Image Pyramid Transformer -- 3-level hierarchical ViT with DINO
# self-supervised pretraining for gigapixel whole-slide images (Chen, Chen et al.,
# CVPR 2022 Oral). The `Mlp`, `Attention`, `Block`, `PatchEmbed`, `VisionTransformer`
# (ViT-256, mostly copy-paste from the `timm` library per the repo's own docstring)
# and `VisionTransformer4K` (ViT-4K, operates over a grid of ViT-256 [CLS] tokens
# instead of raw pixels) classes below are copied verbatim from the official repo's
# vision_transformer.py / vision_transformer4k.py. The `HIPT_4K_Staging` class below
# reproduces the real `HIPT_4K.forward` method from HIPT_4K/hipt_4k.py verbatim
# (unfold image into 256x256 patches -> ViT-256 per-patch [CLS] tokens -> reshape into
# a feature grid -> ViT-4K [CLS] token), with only the pretrained-checkpoint loading
# (`get_vit256`/`get_vit4k` in hipt_model_utils.py, which needs h5py/matplotlib/
# skimage/webdataset just to import the file) and the heatmap/attention-visualization
# methods dropped -- those are I/O and plotting utilities orthogonal to the forward
# architecture, not part of the model definition. No architectural layer was changed;
# the third hierarchy level (WSI-level aggregation over many ViT-4K region embeddings,
# via a GRU/attention head trained separately -- see 2-Weakly-Supervised-Subtyping/) is
# outside the scope of a single forward pass and is not part of `HIPT_4K.forward`.
"""Vendored HIPT model definition (VisionTransformer, VisionTransformer4K, HIPT_4K)."""

import math
from functools import partial

import torch
import torch.nn as nn
from einops import rearrange
from torchvision import transforms

MENAGERIE_ZOO = "vendored-pytorch"


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)  # noqa: E741
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob: float = 0.0, training: bool = False):
    if drop_prob == 0.0 or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks)."""

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class Mlp(nn.Module):
    def __init__(
        self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.0
    ):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(
        self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0.0, proj_drop=0.0
    ):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim**-0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, N, C = x.shape
        qkv = (
            self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        )
        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x, attn


class Block(nn.Module):
    def __init__(
        self,
        dim,
        num_heads,
        mlp_ratio=4.0,
        qkv_bias=False,
        qk_scale=None,
        drop=0.0,
        attn_drop=0.0,
        drop_path=0.0,
        act_layer=nn.GELU,
        norm_layer=nn.LayerNorm,
    ):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim,
            num_heads=num_heads,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            attn_drop=attn_drop,
            proj_drop=drop,
        )
        self.drop_path = DropPath(drop_path) if drop_path > 0.0 else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(
            in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop
        )

    def forward(self, x, return_attention=False):
        y, attn = self.attn(self.norm1(x))
        if return_attention:
            return attn
        x = x + self.drop_path(y)
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class PatchEmbed(nn.Module):
    """Image to Patch Embedding."""

    def __init__(self, img_size=224, patch_size=16, in_chans=3, embed_dim=768):
        super().__init__()
        num_patches = (img_size // patch_size) * (img_size // patch_size)
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches

        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)

    def forward(self, x):
        B, C, H, W = x.shape
        x = self.proj(x).flatten(2).transpose(1, 2)
        return x


class VisionTransformer(nn.Module):
    """Vision Transformer (ViT-256): mostly copy-paste from the `timm` library."""

    def __init__(
        self,
        img_size=[224],
        patch_size=16,
        in_chans=3,
        num_classes=0,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4.0,
        qkv_bias=False,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        norm_layer=nn.LayerNorm,
        **kwargs,
    ):
        super().__init__()
        self.num_features = self.embed_dim = embed_dim

        self.patch_embed = PatchEmbed(
            img_size=img_size[0], patch_size=patch_size, in_chans=in_chans, embed_dim=embed_dim
        )
        num_patches = self.patch_embed.num_patches

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.zeros(1, num_patches + 1, embed_dim))
        self.pos_drop = nn.Dropout(p=drop_rate)

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]
        self.blocks = nn.ModuleList(
            [
                Block(
                    dim=embed_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate,
                    attn_drop=attn_drop_rate,
                    drop_path=dpr[i],
                    norm_layer=norm_layer,
                )
                for i in range(depth)
            ]
        )
        self.norm = norm_layer(embed_dim)

        self.head = nn.Linear(embed_dim, num_classes) if num_classes > 0 else nn.Identity()

        trunc_normal_(self.pos_embed, std=0.02)
        trunc_normal_(self.cls_token, std=0.02)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=0.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def interpolate_pos_encoding(self, x, w, h):
        npatch = x.shape[1] - 1
        N = self.pos_embed.shape[1] - 1
        if npatch == N and w == h:
            return self.pos_embed
        class_pos_embed = self.pos_embed[:, 0]
        patch_pos_embed = self.pos_embed[:, 1:]
        dim = x.shape[-1]
        w0 = w // self.patch_embed.patch_size
        h0 = h // self.patch_embed.patch_size
        w0, h0 = w0 + 0.1, h0 + 0.1
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(
                0, 3, 1, 2
            ),
            scale_factor=(w0 / math.sqrt(N), h0 / math.sqrt(N)),
            mode="bicubic",
        )
        assert int(w0) == patch_pos_embed.shape[-2] and int(h0) == patch_pos_embed.shape[-1]
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        return torch.cat((class_pos_embed.unsqueeze(0), patch_pos_embed), dim=1)

    def prepare_tokens(self, x):
        B, nc, w, h = x.shape
        x = self.patch_embed(x)

        cls_tokens = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)

        x = x + self.interpolate_pos_encoding(x, w, h)

        return self.pos_drop(x)

    def forward(self, x):
        x = self.prepare_tokens(x)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        return x[:, 0]

    def get_last_selfattention(self, x):
        x = self.prepare_tokens(x)
        for i, blk in enumerate(self.blocks):
            if i < len(self.blocks) - 1:
                x = blk(x)
            else:
                return blk(x, return_attention=True)

    def get_intermediate_layers(self, x, n=1):
        x = self.prepare_tokens(x)
        output = []
        for i, blk in enumerate(self.blocks):
            x = blk(x)
            if len(self.blocks) - i <= n:
                output.append(self.norm(x))
        return output


def vit_small(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size,
        embed_dim=384,
        depth=12,
        num_heads=6,
        mlp_ratio=4,
        qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6),
        **kwargs,
    )
    return model


class VisionTransformer4K(nn.Module):
    """Vision Transformer 4K (ViT-4K): operates on a feature grid of ViT-256 [CLS] tokens."""

    def __init__(
        self,
        num_classes=0,
        img_size=[224],
        input_embed_dim=384,
        output_embed_dim=192,
        depth=12,
        num_heads=12,
        mlp_ratio=4.0,
        qkv_bias=False,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        norm_layer=nn.LayerNorm,
        num_prototypes=64,
        **kwargs,
    ):
        super().__init__()
        embed_dim = output_embed_dim
        self.num_features = self.embed_dim = embed_dim
        self.phi = nn.Sequential(
            *[nn.Linear(input_embed_dim, output_embed_dim), nn.GELU(), nn.Dropout(p=drop_rate)]
        )
        num_patches = int(img_size[0] // 16) ** 2

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.zeros(1, num_patches + 1, embed_dim))
        self.pos_drop = nn.Dropout(p=drop_rate)

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]
        self.blocks = nn.ModuleList(
            [
                Block(
                    dim=embed_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate,
                    attn_drop=attn_drop_rate,
                    drop_path=dpr[i],
                    norm_layer=norm_layer,
                )
                for i in range(depth)
            ]
        )
        self.norm = norm_layer(embed_dim)

        self.head = nn.Linear(embed_dim, num_classes) if num_classes > 0 else nn.Identity()

        trunc_normal_(self.pos_embed, std=0.02)
        trunc_normal_(self.cls_token, std=0.02)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=0.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def interpolate_pos_encoding(self, x, w, h):
        npatch = x.shape[1] - 1
        N = self.pos_embed.shape[1] - 1
        if npatch == N and w == h:
            return self.pos_embed
        class_pos_embed = self.pos_embed[:, 0]
        patch_pos_embed = self.pos_embed[:, 1:]
        dim = x.shape[-1]
        w0 = w // 1
        h0 = h // 1
        w0, h0 = w0 + 0.1, h0 + 0.1
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(
                0, 3, 1, 2
            ),
            scale_factor=(w0 / math.sqrt(N), h0 / math.sqrt(N)),
            mode="bicubic",
        )
        assert int(w0) == patch_pos_embed.shape[-2] and int(h0) == patch_pos_embed.shape[-1]
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        return torch.cat((class_pos_embed.unsqueeze(0), patch_pos_embed), dim=1)

    def prepare_tokens(self, x):
        self.mpp_feature = x
        B, embed_dim, w, h = x.shape
        x = x.flatten(2, 3).transpose(1, 2)

        x = self.phi(x)

        cls_tokens = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)

        x = x + self.interpolate_pos_encoding(x, w, h)

        return self.pos_drop(x)

    def forward(self, x):
        x = self.prepare_tokens(x)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        return x[:, 0]

    def get_last_selfattention(self, x):
        x = self.prepare_tokens(x)
        for i, blk in enumerate(self.blocks):
            if i < len(self.blocks) - 1:
                x = blk(x)
            else:
                return blk(x, return_attention=True)

    def get_intermediate_layers(self, x, n=1):
        x = self.prepare_tokens(x)
        output = []
        for i, blk in enumerate(self.blocks):
            x = blk(x)
            if len(self.blocks) - i <= n:
                output.append(self.norm(x))
        return output


def vit4k_xs(**kwargs):
    model = VisionTransformer4K(
        input_embed_dim=384,
        output_embed_dim=192,
        depth=6,
        num_heads=6,
        mlp_ratio=4,
        qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6),
        **kwargs,
    )
    return model


class HIPT_4K_Staging(nn.Module):
    """HIPT Model (ViT-4K) for encoding non-square images with [256 x 256] patch
    tokens, with [256 x 256] patch tokens encoded via ViT-256 using [16 x 16] patch
    tokens. Reproduces `HIPT_4K.forward` from HIPT_4K/hipt_4k.py verbatim (random-init
    ViT-256/ViT-4K submodules in place of the checkpoint-loaded `get_vit256`/
    `get_vit4k` helpers; single-device forward instead of the repo's 2-GPU split)."""

    def __init__(self, model256, model4k, img_size4k=[224]):
        super().__init__()
        self.model256 = model256
        self.model4k = model4k
        # ViT-4K's positional embedding grid is sized to img_size4k // 16; the
        # forward's feature grid (w_256 x h_256, one ViT-256 [CLS] per 256x256 patch)
        # must match that count, i.e. w_256*16 == img_size4k[0] (see hipt_4k.py's own
        # note: "w_256, h_256" naming is really "# of patch-tokens fed to ViT-4K").

    def prepare_img_tensor(self, img: torch.Tensor, patch_size=256):
        make_divisble = lambda l, ps: l - (l % ps)  # noqa: E731, E741
        b, c, w, h = img.shape
        load_size = make_divisble(w, patch_size), make_divisble(h, patch_size)
        w_256, h_256 = w // patch_size, h // patch_size
        img_new = transforms.CenterCrop(load_size)(img)
        return img_new, w_256, h_256

    def forward(self, x):
        """
        Forward pass of HIPT (given an image tensor x), outputting the [CLS] token
        from ViT-4K.
        1. x is center-cropped such that the W / H is divisible by the patch token
           size in ViT-4K (e.g. - 256 x 256).
        2. x then gets unfolded into a "batch" of [256 x 256] images.
        3. A ViT-256 model extracts the CLS token from each [256 x 256] image in the
           batch.
        4. These batch-of-features are then reshaped into a 2D feature grid (of width
           "w_256" and height "h_256").
        5. This feature grid is then used as the input to ViT-4K, outputting [CLS]_4K.
        """
        batch_256, w_256, h_256 = self.prepare_img_tensor(x)
        batch_256 = batch_256.unfold(2, 256, 256).unfold(3, 256, 256)
        batch_256 = rearrange(batch_256, "b c p1 p2 w h -> (b p1 p2) c w h")

        features_cls256 = []
        for mini_bs in range(0, batch_256.shape[0], 256):
            minibatch_256 = batch_256[mini_bs : mini_bs + 256]
            features_cls256.append(self.model256(minibatch_256))

        features_cls256 = torch.vstack(features_cls256)
        features_cls256 = (
            features_cls256.reshape(w_256, h_256, 384)
            .transpose(0, 1)
            .transpose(0, 2)
            .unsqueeze(dim=0)
        )
        features_cls4k = self.model4k.forward(features_cls256)
        return features_cls4k


def build_hipt4k():
    # Real repo defaults (get_vit256/get_vit4k in hipt_model_utils.py): ViT-256 is
    # `vit_small(patch_size=16, num_classes=0)`; ViT-4K is `vit4k_xs(num_classes=0)`
    # (input_embed_dim=384 matches ViT-256's embed_dim). img_size4k=[256] means ViT-4K
    # expects a 16x16 feature-token grid (256 // 16), i.e. a 256x256-patch input image
    # of 4096x4096 pixels in the real pipeline; scaled down here to keep the trace fast
    # while preserving the exact hierarchical composition.
    model256 = vit_small(patch_size=16, num_classes=0)
    model4k = vit4k_xs(img_size=[256], num_classes=0)
    model256.eval()
    model4k.eval()
    model = HIPT_4K_Staging(model256, model4k, img_size4k=[256])
    model.eval()
    return model


def example_input_hipt4k():
    # 1024x1024 region -> 4x4 grid of 256x256 patches -> 16 ViT-256 [CLS] tokens
    # (matches ViT-4K's 16x16=256... scaled: img_size4k=[256] expects a 16x16 grid of
    # *tokens*, but at 1024x1024 input we get a 4x4=16-token grid, which ViT-4K's
    # `interpolate_pos_encoding` handles via bicubic resize when npatch != N).
    return (torch.randn(1, 3, 1024, 1024),)


MENAGERIE_ENTRIES = [
    ("HIPT", build_hipt4k, example_input_hipt4k, 2022, "vendored-pytorch"),
]
