"""GCNN-P4: group-equivariant CNN over translations and 90-degree rotations.

Paper: Group Equivariant Convolutional Networks, Cohen and Welling, ICML 2016.

The defining primitive is group convolution on P4, the group generated by image
translations and rotations by 0, 90, 180, and 270 degrees.  This compact model lifts
Z2 images to P4 feature maps, applies P4-to-P4 convolutions by rotating filters across
both input and output orientations, then pools over the group.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


def _rotate_kernel(weight: torch.Tensor, turns: int) -> torch.Tensor:
    """Rotate a convolution kernel by quarter turns.

    Parameters
    ----------
    weight:
        Kernel tensor.
    turns:
        Number of 90-degree rotations.

    Returns
    -------
    torch.Tensor
        Rotated kernel.
    """

    return torch.rot90(weight, turns, dims=(-2, -1))


class P4LiftConv(nn.Module):
    """Lift a planar image into four orientation channels."""

    def __init__(self, in_channels: int, out_channels: int) -> None:
        """Initialize the shared planar filter bank.

        Parameters
        ----------
        in_channels:
            Number of image channels.
        out_channels:
            Number of group feature channels.
        """

        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_channels, in_channels, 3, 3) * 0.05)
        self.bias = nn.Parameter(torch.zeros(out_channels))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply Z2-to-P4 lifting convolution.

        Parameters
        ----------
        x:
            Image tensor ``(batch, channels, height, width)``.

        Returns
        -------
        torch.Tensor
            P4 feature map ``(batch, channels, 4, height, width)``.
        """

        outs = []
        for r in range(4):
            y = F.conv2d(x, _rotate_kernel(self.weight, r), self.bias, padding=1)
            outs.append(y)
        return torch.stack(outs, dim=2)


class P4GroupConv(nn.Module):
    """P4-to-P4 group convolution with cyclic orientation mixing."""

    def __init__(self, in_channels: int, out_channels: int) -> None:
        """Initialize orientation-indexed filters.

        Parameters
        ----------
        in_channels:
            Input channels per orientation.
        out_channels:
            Output channels per orientation.
        """

        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_channels, in_channels, 4, 3, 3) * 0.04)
        self.bias = nn.Parameter(torch.zeros(out_channels))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply cyclic P4 group convolution.

        Parameters
        ----------
        x:
            P4 feature map ``(batch, channels, 4, height, width)``.

        Returns
        -------
        torch.Tensor
            P4 feature map.
        """

        outs = []
        for r_out in range(4):
            acc = None
            for r_in in range(4):
                rel = (r_in - r_out) % 4
                w = _rotate_kernel(self.weight[:, :, rel], r_out)
                y = F.conv2d(x[:, :, r_in], w, None, padding=1)
                acc = y if acc is None else acc + y
            outs.append(acc + self.bias.view(1, -1, 1, 1))
        return torch.stack(outs, dim=2)


class GCNNP4(nn.Module):
    """Compact P4-equivariant classifier."""

    def __init__(self, classes: int = 10) -> None:
        """Initialize the P4 network.

        Parameters
        ----------
        classes:
            Number of output classes.
        """

        super().__init__()
        self.lift = P4LiftConv(3, 8)
        self.gconv1 = P4GroupConv(8, 12)
        self.gconv2 = P4GroupConv(12, 12)
        self.head = nn.Linear(12, classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Classify images using group-pooled P4 features.

        Parameters
        ----------
        x:
            Image tensor.

        Returns
        -------
        torch.Tensor
            Class logits.
        """

        g = F.relu(self.lift(x))
        g = F.relu(self.gconv1(g))
        g = F.relu(self.gconv2(g))
        pooled = g.mean(dim=(2, 3, 4))
        return self.head(pooled)


def build() -> nn.Module:
    """Build compact GCNN-P4.

    Returns
    -------
    nn.Module
        Random-init P4-equivariant classifier.
    """

    return GCNNP4()


def example_input() -> torch.Tensor:
    """Create a small RGB image batch.

    Returns
    -------
    torch.Tensor
        Example image input ``(1, 3, 24, 24)``.
    """

    return torch.randn(1, 3, 24, 24)


MENAGERIE_ENTRIES = [
    (
        "GCNN_P4",
        "build",
        "example_input",
        "2016",
        "vision/equivariant",
    ),
]
