{
  "name": "menagerie-detect-misc",
  "channels": ["pytorch", "conda-forge", "nodefaults"],
  "dependencies": ["python>=3.10,<3.12", "pytorch>=2.1,<2.2", "torchvision", "detectron2", "mmengine", "mmcv<2.2", "mmdet", "opencv", "pycocotools", "ninja", "cmake", "cxx-compiler"]
}
