name: Lint and Test
on:
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.head_ref || github.ref }}-lint-and-test"
  cancel-in-progress: true

jobs:
#   flake8:
#     runs-on: ubuntu-latest
#     container: python:3.8.5-slim-buster
#     steps:
#       - uses: actions/checkout@v2
#       - run: pip install flake8
#       - run: flake8 . --show-source
  black:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v2
      - run: pip install black
      - run: black --check .
#   mypy:
#     runs-on: ubuntu-latest
#     container: python:3.8.5-slim-buster
#     steps:
#       - uses: actions/checkout@v2
#       - run: pip install mypy types-requests types-redis types-python-slugify
#       - run: mypy --install-types --non-interactive --show-error-codes --raise-exceptions app
  pytest:
    runs-on: ubuntu-latest
    needs: [black] #, flake8, mypy]
    container: python:3.9-slim

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: req-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test
        run: pytest
